swagger: "2.0" # realized based on Swagger 2.0 version
info:
  version: v1
  title: binlog Log
  description: "binlog Log Related API"
basePath: /regions/{regionId}
paths:
  "/instances/{instanceId}/binlogs": #binlog Log
    get:
      description: "Obtain the details of the binlog in the MySQL instance <br>- only support MySQL"
      operationId: describeBinlogs
      x-jdcloud-internal: true
      parameters:
        - name: pageNumber
          required: true
          in: query
          type: integer
          description: "Display the page number of the data. The default is 1, and the value range is [-1, ∞). When pageNumber is -1, return all data page numbers; when the total number of pages is exceeded, display the last page."
        - name: pageSize
          required: true
          in: query
          type: integer
          description: "The default of the number of data displayed per page is 10, and the value range is [1,100], which can only be a multiple of 10."
        - name: startTime
          required: false
          in: query
          type: string
          description: "The format of query start time of is: YYYY-MM-DD HH:mm:ss"
        - name: endTime
          required: false
          in: query
          type: string
          description: "The format of query end time is: YYYY-MM-DD HH:mm:ss"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  totalCount:
                    type: integer
                    description: "Total Number of Records"
                  binlogs:
                    type: array
                    description: "Backup Collection"
                    items:
                      $ref: ../model/Binlog.yaml#/definitions/Binlog
  "/instances/{instanceId}/binlogs/{binlogBackupId}:describeBinlogDownloadURL": #binlog log
    get:
      description: "Obtain the download link of  binlog which is the MySQL instance<br> - only support MySQL"
      operationId: describeBinlogDownloadURL
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  publicURL:
                    type: string
                    description: "Download Link of Public Network"
                  internalURL:
                    type: string
                    description: "Download Link of Intranet"
  "/instances/{instanceId}/binlogs:clearBinlogs": #binlog Log
    post:
      description: "Clear up the Local binlog and Release Space The system will only clear up the binlog that has been backed up to the storage, and will not affect the backup restoration of the MySQL instance<br>- only support MySQL"
      operationId: clearBinlogs
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region code, with range detailed in [Regions and Availability Zone Comparison Table](../Enum-Definitions/Regions-AZ.md)"
  instanceId:
    name: instanceId
    in: path
    required: true
    type: string
    description: "RDS instance ID, which uniquely identifies an RDS instance"
  binlogBackupId:
    name: binlogBackupId
    in: path
    required: true
    type: string
    description: "The backup ID of binlog can be obtained by describeBinlogs"