swagger: "2.0" # realized based on Swagger 2.0 version
info:
  version: v1
  title: Error Logs
  description: "Error Log Related API"
basePath: /regions/{regionId}
paths:
  "/instances/{instanceId}/errorLogs": #Error Logs
    get:
      description: "Obtain error logs of SQL Server and download information<br>- only support SQL Server"
      operationId: describeErrorLogs
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  errorLogs:
                    type: array
                    description: "Collection of Error Log Files"
                    items:
                      $ref: ../model/ErrorLog.yaml#/definitions/ErrorLog
# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region code, with range detailed in [Regions and Availability Zone Comparison Table](../Enum-Definitions/Regions-AZ.md)"
  instanceId:
    name: instanceId
    in: path
    required: true
    type: string
    description: "RDS instance ID, which uniquely identifies an RDS instance"