swagger: "2.0" # realized based on Swagger 2.0 version
info:
  version: v1
  title: Cloud on Single Database
  description: "Cloud on Single Database Related API"

basePath: /regions/{regionId}

paths:
  "/instances/{instanceId}/importFiles": #Files of Cloud on Single Database
    get:
      description: "Obtain the list of files uploaded by the user to the instance through Cloud on Single Database<br>- only support SQL Server"
      operationId: describeImportFiles
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  importFiles:
                    type: array
                    description: "Collection of Imported Files"
                    items:
                      $ref: ../model/ImportFile.yaml#/definitions/ImportFile
  "/instances/{instanceId}/importFiles:getUploadKey": #The Required Key for Uploading the Import File
    post:
      description: "Obtain the required key for uploading files from Cloud on Single Database. Cloud on Single Database needs the correct key value to connect to JD Cloud<br>- only support SQL Server"
      operationId: getUploadKey
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  key:
                    type: string
                    description: "The Key to be used to upload the file"
  "/instances/{instanceId}/importFiles/{fileName}:setShared": #Cloud on Single Database
    post:
      description: "Set or cancel whether the uploaded file is shared to other instances under the same account. By default, files are only visible and can be imported on the uploaded instance. Other instances are not visible and cannot be imported. If you need this file to be imported on other instances, you can set this file to share<br>- only support SQL Server"
      operationId: setImportFileShared
      parameters:
        - name: shared
          in: body
          description: "Whether the file is shared"
          schema:
            type: object
            required:
              - shared
            properties:
              shared:
                type: string
                description: "Whether the file is shared<br>true: shared<br>false: not shared"
      responses:
        200:
          description: OK

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region code, with range detailed in [Regions and Availability Zone Comparison Table](../Enum-Definitions/Regions-AZ.md)"
  instanceId:
    name: instanceId
    in: path
    required: true
    type: string
    description: "RDS instance ID, which uniquely identifies an RDS instance"
  fileName:
    name: fileName
    in: path
    required: true
    type: string
    description: "The File Name of Cloud on Single Database"

