swagger: "2.0" # realized based on Swagger 2.0 version
info:
  version: v1
  title: Performance Statistics
  description: "Performance Statistics Related API"
basePath: /regions/{regionId}
paths:
  "/instances/{instanceId}/performance:describeIndexPerformance": #Index Performance Statistics
    post:
      description: "Obtain statistics on index performance based on user-defined query conditions, and provide missing indexes and suggestions for index creation. Users can use these information to find index-related performance bottlenecks and optimize them. <br>- Support SQL Server Only"
      operationId: describeIndexPerformance
      parameters:
        - name: queryType
          required: true
          in: query
          type: string
          description: "Query Type, Return Results of Fields From High to Low for Different Query Types. <br>The following types are supported:<br>Missing: Index missing<br>Size: Index size, unit KB<br>Updates: Index updates<br>Scans: Table scan times<br>Used: Least used|<br>"
        - name: db
          required: false
          in: query
          type: string
          description: "Multiple names of the database to be queried are separated by commas and all databases are by default."
        - name: pageNumber
          required: false
          in: query
          type: integer
          description: "The default of the page number of the data displayed is 1 and the value range is [-1,1000). When pageNumber is -1, return all data page numbers; when the total number of pages is exceeded, display the last page."
        - name: pageSize
          required: false
          in: query
          type: integer
          description: "The default of the number of data displayed per page is 50 and the value range is [1,100]. It can only be a multiple of 10 used for the API to query the list."
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  missingIndexResult:
                    type: array
                    description: "When queryType is Missing, the result set is MissingIndexResult<br>when queryType is other values, the field is null."
                    items:
                      $ref: ../model/MissingIndexResult.yaml#/definitions/MissingIndexResult
                  indexPerformanceResult:
                    type: array
                    description: "When the queryType is Missing, the field is empty <br>when the queryType is other values, return IndexPerformanceResult"
                    items:
                      $ref: ../model/IndexPerformanceResult.yaml#/definitions/IndexPerformanceResult
                  totalCount:
                    type: integer
                    description: "Total Number of Records"
                  pageNumber:
                    type: integer
                    description: "The Page Number of the Current Data"
                  pageSize:
                    type: integer
                    description: "The Number of Data Displayed Per Page"
  "/instances/{instanceId}/performance:describeQueryPerformance": #Query Performance Statistics
    post:
      description: "Obtain the information of performance statistics of SQL execution, such as slow SQL, etc. based on user-defined query conditions. Based on this information, users can find and optimize performance bottlenecks related to SQL execution. <br>- Support SQL Server Only"
      operationId: describeQueryPerformance
      parameters:
        - name: queryType
          required: true
          in: query
          type: string
          description: "Query Type, Return Results of Fields From High to Low for Different Query Types. <br>support the following types: <br>ExecutionCount: Number of executions<br>LastRows: Number of rows returned last time<br>ElapsedTime: Average execution time<br>CPUTime: Average CPU time<br>LogicalReads: Average logical read<br>LogicalWrites: Average logical write<br>PhysicalReads: Average physical read<br>"
        - name: threshold
          required: false
          in: query
          type: integer
          description: "Return only records whose query condition is larger than or equal to threshold and the default is 0"
        - name: pageNumber
          required: false
          in: query
          type: integer
          description: "The default of the number of the data displayed is 1 and the value range is [-1,1000]. When pageNumber is -1, return all data page numbers; when the total number of pages is exceeded, display the last page."
        - name: pageSize
          required: false
          in: query
          type: integer
          description: "The default of the number of data displayed per page is 50 and the value range is [1,100]. It can only be a multiple of 10 used for the API to query the list."
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  queryPerformanceResult:
                    type: array
                    description: "The Result Set of Query Performance Statistics"
                    items:
                      $ref: ../model/QueryPerformanceResult.yaml#/definitions/QueryPerformanceResult
                  totalCount:
                    type: integer
                    description: "Total Number of Records"
                  pageNumber:
                    type: integer
                    description: "The Page Number of the Current Data"
                  pageSize:
                    type: integer
                    description: "The Number of Data Displayed Per Page"
# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region code, with range detailed in [Regions and Availability Zone Comparison Table](../Enum-Definitions/Regions-AZ.md)"
  instanceId:
    name: instanceId
    in: path
    required: true
    type: string
    description: "RDS instance ID, which uniquely identifies an RDS instance"