swagger: "2.0" # realized based on Swagger 2.0 version
info:
  version: v1
  title: White List
  description: "White List Related API"
basePath: /regions/{regionId}
paths:
  "/instances/{instanceId}/whiteList": #Instance IP white list
    put:
      description: "Modify the IP White List that allows access to the instance. The White List is a list of IP/IP segments that are allowed to access the current instance. By default, the White List is open to the VPC. If the user has enabled the internet access, you need to configure a White List for the IP of the internet."
      operationId: modifyWhiteList
      #x-jdcloud-internal: true
      parameters:
        - name: ips
          required: true
          in: query
          type: string
          description: "For IP or IP segment, different IP/IP segments shall be separated by commas, for example 0.0.0.0/0,192.168.0.10"
      responses:
        200:
          description: OK
    get:
      description: "View the current White List of RDS instances. The White List is a list of IP/IP segments that are allowed to access the current instance. By default, the White List is open to the VPC. If the user has enabled the internet access, you need to configure a White List for the IP of the internet."
      operationId: describeWhiteList
      #x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  whiteLists:
                    type: array
                    description: "White List"
                    items:
                      $ref: ../model/WhiteList.yaml#/definitions/WhiteList
# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region code, with range detailed in [Regions and Availability Zone Comparison Table](../Enum-Definitions/Regions-AZ.md)"
  instanceId:
    name: instanceId
    in: path
    required: true
    type: string
    description: "RDS instance ID, which uniquely identifies an RDS instance"