swagger: "2.0"
definitions:
  Account:
    x-jdcloud-module: rds
    title: Account
    type: object
    properties:
      accountName:
        type: string
        description: "Account name with specific rules detailed in the Help Center Documentation: [Name and Password Restrictions](../../../documentation/Cloud-Database-and-Cache/RDS/Introduction/Restrictions/SQLServer-Restrictions.md)"
      accountStatus:
        type: string
        description: "Account status, detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)<br>- **MySQL: Not support, not return this field**<br>- **SQL Server: return this field**"
      accountPrivileges:
        type: array
        items:
          $ref: "../model/AccountPrivilege.yaml#/definitions/AccountPrivilege"
          description: "Account Privilege"
        description: "Specific Privilege"