swagger: "2.0"
definitions:
  AccountPrivilege:
    x-jdcloud-module: rds
    title: AccountPrivilege
    type: object
    properties:
      dbName:
        type: string
        description: "Database name with specific rules detailed in the Help Center Documentation: [Name and Password Restrictions](../../../documentation/Cloud-Database-and-Cache/RDS/Introduction/Restrictions/SQLServer-Restrictions.md)"
      privilege:
        type: string
        description: "Privilege of account to the database with the specific definition detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)"