swagger: "2.0"
definitions:
  Backup:
    x-jdcloud-module: rds
    title: Backup
    type: object
    properties:
      backupId:
        type: string
        description: "Backup ID"
      backupName:
        type: string
        description: "Backup name with length up to 64 English characters or Chinese characters of equal length"
      instanceId:
        type: string
        description: "Backup Instance ID"
      backupStatus:
        type: string
        description: "Backup Status, detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)"
      backupStartTime:
        type: string
        description: "Backup Start Time, Format: YYYY-MM-DD HH:mm:ss"
      backupEndTime:
        type: string
        description: "Backup End Time, Format: YYYY-MM-DD HH:mm:ss"
      backupType:
        type: string
        description: "Backup type, full backup or incremental backup, detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)<br>- **SQL Server supports****<br>- **MySQL does not support**"
      backupMode:
        type: string
        description: "Backup mode, automatic system backup or manual backup, detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)"
      backupUnit:
        type: string
        description: "Backup granularity, instance backup or multi-database backup, detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)<br>- **SQL Server supports**<br>- **MySQL does not support**"
      backupFiles:
        type: array
        items:
          type: string
          description: "Backup File Name"
        description: "Backup File List<br>- **SQL Server supports**, there can be multiple backup files and the naming rules for file name are:<br>(1) Full: Database name +.bak<br>(2) Incremental: Database name +.diff<br>- **MySQL does not support**"
      backupSizeByte:
        type: integer
        description: "Size of Whole Backup Set, Unit: Byte"