swagger: "2.0"
definitions:
  backupSpec:
    x-jdcloud-module: rds
    title: backupSpec
    type: object
    properties:
      backupName:
        type: string
        description: "Backup name with length up to 64 English characters or Chinese characters of equal length"
      dbNames:
        type: array
        items:
          type: string
        description: "List of Database Names to Be Backed up. If it is not filled, the whole instance will be backed up<br>- **MySQL: not support the parameter**<br>- **SQL Server: support**"