swagger: "2.0"
definitions:
  DBInstanceAttribute:
    x-jdcloud-module: rds
    title: DBInstanceAttribute
    type: object
    properties:
      instanceId:
        type: string
        description: "Instance ID"
      instanceName:
        type: string
        description: "Instance name with specific rules detailed in the Help Center Documentation: [Name and Password Restrictions](../../../documentation/Cloud-Database-and-Cache/RDS/Introduction/Restrictions/SQLServer-Restrictions.md)"
      instanceType:
        type: string
        description: "Instance type, such as primary instances, read-only instances, etc., detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)"
      engine:
        type: string
        description: "Instance engine type, such as MySQL or SQL Server, etc., detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)"
      engineVersion:
        type: string
        description: "Instance engine version, detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)"
      instanceClass:
        type: string
        description: "Instance Type Code"
      instanceStorageGB:
        type: integer
        description: "Disk, Unit: GB"
      instanceCPU:
        type: integer
        description: "Number of CPU Cores"
      instanceMemoryMB:
        type: integer
        description: "Memory Size, Unit: MB"
      regionId:
        type: string
        description: "Region ID, detailed in [Regions and Availability Zone Comparison Table](../Enum-Definitions/Regions-AZ.md)"
      azId:
        type: array
        items:
          type: string
          description: "AZ ID"
        description: "AZ ID, the first is AZ for the primary instance, which is detailed in [Regions and Availability Zone Comparison Table](../Enum-Definitions/Regions-AZ.md)"
      vpcId:
        type: string
        description: "VPC ID"
      subnetId:
        type: string
        description: "Subnet ID"
      internalDomainName:
        type: string
        description: "Instance Public Network Domain Name"
      publicDomainName:
        type: string
        description: "Instance Intranet Domain Name"
      instancePort:
        type: string
        description: "Application Access Port"
      connectionMode:
        type: string
        description: "Access  Mode, detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)"
      auditStatus:
        type: string
        description: "Audit status, detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)"
      instanceStatus:
        type: string
        description: "Instance status, detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)"
      createTime:
        type: string
        description: "Instance Creation Time"
      charge:
        $ref: "../../charge/model/Charge.yaml#/definitions/charge"
        description: "Billing Configuration"
      #ROInstanceIds:
        #type: array
        #items:
          #type: string
          #description: Read-only Instance ID
        #description: Read-only Instance ID List