swagger: "2.0"
definitions:
  DBInstanceSpec:
    x-jdcloud-module: rds
    title: DBInstanceSpec
    type: object
    required:
      - engine
      - engineVersion
      - instanceClass
      - instanceStorageGB
      - azId
      - vpcId
      - subnetId
      - chargeSpec
    properties:
      instanceName:
        type: string
        description: "Instance name with specific rules detailed in the Help Center Documentation: [Name and Password Restrictions](../../../documentation/Cloud-Database-and-Cache/RDS/Introduction/Restrictions/SQLServer-Restrictions.md)"
      engine:
        type: string
        description: "Instance engine type, detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)"
      engineVersion:
        type: string
        description: "Instance engine version, detailed in [Enumeration Parameter Definition](../Enum-Definitions/Enum-Definitions.md)"
      instanceClass:
        type: string
        description: "Instance type code, which can be obtained through [describeInstanceClasses](../instance/describeInstanceClasses.md) API"
      instanceStorageGB:
        type: integer
        description: "Disk Size, Unit: GB"
      azId:
        type: array
        items:
          type: string
          description: "AZ ID"
        description: "AZ ID, the first ID must be AZ where the primary instance is located. If the two AZs are the same, you also need to enter two azIds."
      vpcId:
        type: string
        description: "VPC ID"
      subnetId:
        type: string
        description: "Subnet ID"
      chargeSpec:
        $ref: "../../charge/model/ChargeSpec.yaml#/definitions/chargeSpec"
        description: "Billing specification, including billing type, billing period, etc."