swagger: "2.0"
definitions:
  ErrorLog:
    x-jdcloud-module: rds
    title: ErrorLog
    type: object
    properties:
      name:
        type: string
        description: "Error Log File Name"
      sizeByte:
        type: integer
        format: int64
        description: "Error Log File Size in Bytes"
      lastUpdateTime:
        type: string
        description: "Last Update Time of the Error Log, Format: YYYY-MM-DD HH:mm:ss"
      uploadTime:
        type: string
        description: "Error Log Upload Time, Format: YYYY-MM-DD HH:mm:ss"
      publicURL:
        type: string
        description: "Download Link of Public Network"
      internalURL:
        type: string
        description: "Download Link of Intranet"