swagger: "2.0"
definitions:
  File:
    x-jdcloud-module: rds
    title: File
    type: object
    properties:
      name:
        type: string
        description: "File Name"
      sizeByte:
        type: integer
        description: "File Size, Unit: Byte"
