swagger: "2.0"
definitions:
  FileDownloadURL:
    x-jdcloud-module: rds
    title: FileDownloadURL
    type: object
    properties:
      publicURL:
        type: string
        description: "Public network download link, if download is not available currently, it is an empty string"
      internalURL:
        type: string
        description: "Intranet download link, if download is not available currently, it is an empty string"
      