swagger: "2.0"
definitions:
  RestoredNewDBInstanceSpec:
    x-jdcloud-module: rds
    title: RestoredNewDBInstanceSpec
    type: object
    required:
      - instanceClass
      - instanceStorageGB
      - azId
      - vpcId
      - subnetId
      - chargeSpec
    properties:
      instanceName:
        type: string
        description: "Database instance name with restrictions detailed in the [Help Center Documentation](../../../documentation/Cloud-Database-and-Cache/RDS/Introduction/Restrictions/SQLServer-Restrictions.md)"
      instanceClass:
        type: string
        description: "Instance type code, which can be obtained through [describeInstanceClasses](../instance/describeInstanceClasses.md) API"
      instanceStorageGB:
        type: integer
        description: "Disk Size, Unit: GB"
      azId:
        type: array
        items:
          type: string
          description: "AZ ID"
        description: "AZ ID, the first ID must be AZ where the primary instance is located. If the two AZs are the same, you also need to enter two azIds."
      vpcId:
        type: string
        description: "VPC ID"
      subnetId:
        type: string
        description: "Subnet ID"
      chargeSpec:
        $ref: "../../charge/model/ChargeSpec.yaml#/definitions/chargeSpec"
        description: "Billing specification, including billing type, billing period, etc."