swagger: "2.0"
definitions:
  AttackTypeCount:
    type: object
    x-jdcloud-module: ipanti
    properties:
      type:
        type: string
        description: "Attack Type"
      count:
        type: integer
        description: "Attack Counts"