swagger: "2.0"
definitions:
  CertInfoModifySpec:
    type: object
    x-jdcloud-module: ipanti
    properties:
      httpsCertContent:
        type: string
        description: "Certificate Content"
      httpsRsaKey:
        type: string
        description: "Private Key"