swagger: "2.0"
definitions:
  OriginAddrItem:
    type: object
    x-jdcloud-module: ipanti
    properties:
      ip:
        type: string
        description: "Back-to-origin IP address"
      weight:
        type: integer
        description: "Weight"
      inJdCloud:
        type: boolean
        description: "Confirm whether it is the Private IP/EIP address of JD Cloud?"