swagger: "2.0"
definitions:
  webRule:
    type: object
    x-jdcloud-module: ipanti
    properties:
      id:
        type: integer
        format: int64
        description: "Rule ID"
      instanceId:
        type: integer
        format: int64
        description: "Instance ID"
      domain:
        type: string
        description: "Subdomain"
      cname:
        type: string
        description: "cname of Rules"
      protocol:
        type: string
        description: "Protocol: HTTP, HTTPS and HTTP_HTTPS"
      port:
        type: string
        description: "HTTP protocol port number, such as 80 and 81, and multiple port numbers are separated by commas"
      httpsPort:
        type: string
        description: "HTTPS protocol port number, such as 443 and 8443, and multiple port numbers are separated by commas"
      originType:
        type: string
        description: "Back-to-origin Type: A or CNAME"
      originAddr:
        type: array
        items:
          $ref: "../model/OriginAddrItem.yaml#/definitions/OriginAddrItem"
      onlineAddr:
        type: array
        items:
          type: string
      originDomain:
        type: string
        description: "Back-to-origin domain name, and the field is returned when originType is CNAME"
      httpsCertContent:
        type: string
        description: "Certificate Content"
      httpsRsaKey:
        type: string
        description: "Certificate Private Key"
      httpCertStatus:
        type: integer
        description: "Certificate Status: 0->exceptional  1->normal"
      status:
        type: integer
        description: "0->defense Status  1->back-to-origin Status"
      ccStatus:
        type: integer
        description: "0->CC disabled  1->CC enabled"
      algorithm:
        type: string
        description: "Forwarding Rules: wrr->Round Robin with weight  rr->Round Robin without weight"
      forceJump:
        type: integer
        description: "Confirm to enable https forced jump? The attribute may be configured when the protocol is HTTP_HTTPS  0->no  1->yes"
      customPortStatus:
        type: integer
        description: "Confirm whether it is customized port number or not? 0->default  1->customized"
      httpOrigin:
        type: integer
        description: "Confirm to enable http back-to-origin, 0->no  1->yes. The attribute may be configured when HTTPS is checked"