swagger: "2.0"
info:
  version: "v1"
  title: Elastic IP
  description: "Elastic IP APIs"

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/elasticIps/":
    get:
      operationId: describeElasticIps
      summary: "Query Elastic IP List"
      description: "Query Elastic IP List"
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          minimum: 1
          description: "Page; it is 1 by default. Value Range: [1,∞); when the pages exceed total pages, show the last page"
          
        - name: pageSize
          in: query
          type: integer
          default: 20
          minimum: 10
          maximum: 100
          description: "Paging Size: 20 by default. Value Range: [10, 100]"
          
        - name: filters
          in: query
          type: array
          items:
            #$ref: "/jcloud-open-api/common/model/Filter.yaml#/definitions/filter"
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
            elasticIpIds - ElasticIP ID Array Conditions, Support Multiple IDs
            elasticIpAddress - EIP IP Address, Support Single Address
            chargeStatus	- EIP Payment Status, Normal (normal status) or Overdue (Pay-In-Advance expired) or Arrear(arrear status), Support Single Status

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                description: "Returned Results"
                type: object
                properties:
                  elasticIps:
                    description: "ElasticIp Resource Information List"
                    type: array
                    items:
                      #$ref: "/jcloud-open-api/vpc/model/ElasticIp.yaml#/definitions/elasticIp"
                      $ref: "../model/ElasticIp.yaml#/definitions/elasticIp"
                  totalCount:
                    description: "Total Number"
                    type: integer
              requestId:
                description: "Request ID"
                type: string
        400:
          description: "invalid parameter"
        401:
          description: "Authentication failed"
    
    post:
      summary: "Create One or More Elastic IPs"
      description: "Create One or More Elastic IPs"
      operationId: createElasticIps
      parameters:
        - name: createElasticIpSpec
          in: body
          required: true
          description: "Apply for Creating Elastic IP Request Parameter"
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/CreateElasticIpSpec.yaml#/definitions/createElasticIpSpec"
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              result:
                description: "Returned Results"
                properties:
                  elasticIpIds:
                    description: "Elastic IP ID List"
                    type: array
                    items:
                      type: string
                      description: "Elastic IP ID"
                  requestId:
                    description: "Request ID"
                    type: string
        400:
          description: "Invalid param 'xxx'"
        401:
          description: "Unauthenticated user pin 'xxx'"
        500:
          description: "Unknown server error"
        503:
          description: "Service unavailable"


  "/elasticIps/{elasticIpId}":
      #describe ElasticIp
      get:
        summary: "ElasticIp Resource Information Details"
        description: "ElasticIp Resource Information Details"
        operationId: describeElasticIp
        responses:
          200:
            description: OK
            schema:
              properties:
                result:
                  description: "Returned Results"
                  properties:
                    elasticIp:
                      description: "ElasticIp Resource Information"
                      $ref: "../model/ElasticIp.yaml#/definitions/elasticIp"
                requestId:
                  description: "Request ID"
                  type: string
          400:
            description: "invalid parameter"
          401:
            description: "Authentication failed"
      
      #delete ElasticIp
      delete:
        summary: "Delete Elastic IP"
        description: "Delete Elastic IP"
        operationId: deleteElasticIp
        responses:
          200:
            description: OK
            schema:
              properties:
                requestId:
                  description: "Request ID"
                  type: string
          400:
            description: "Invalid param 'xxx'"
          404:
            description: "elasticIp 'xxx' not found"
          500:
            description: "Unknown server error"
          503:
            description: "Service unavailable"

      patch:
        summary: "Modify Elastic IP"
        description: "Modify Elastic IP"
        x-jdcloud-internal: true
        operationId: modifyElasticIp
        parameters:
          - name: modifyElasticIpSpec
            in: body
            required: true
            description: "Modify Elastic IP"
            x-jdcloud-tiered: false
            schema:
              $ref: "../model/ModifyElasticIpSpec.yaml#/definitions/modifyElasticIpSpec"

        responses:
         200:
            description: Successful operation
            schema:
              type: object
              properties:
                 requestId:
                    description: "Request ID"
                    type: string
         400:
            description: "Invalid param 'xxx'"
         404:
            description: Resource not found
          
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  elasticIpId:
    name: elasticIpId
    in: path
    required: true
    type: string
    description: ElasticIp ID
        

    
