swagger: "2.0"
info:
  version: "v1"
  title: Acl
  description: "Acl APIs"

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/networkAcls/":
    get:
      summary: "Query Acl List"
      description: "Query Acl List"
      operationId: describeNetworkAcls
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          minimum: 1
          description: "Page: 1 by default. Value Range: [1,∞); when the pages exceed total pages, show the last page"
        - name: pageSize
          in: query
          type: integer
          default: 20
          minimum: 10
          maximum: 100
          description: "Paging Size; 20 by default. Value Range: [10, 100]"
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
            description: |
                   networkAclIds - Elastic Network Interface ID List, support multiple IDs
                   networkAclNames - Elastic Network Interface Name List, support multiple names
                   VPCId - VPC ID of Elastic Network Interface, support single ID
                 
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                description: "Returned Results"
                properties:
                  networkAcls:
                    description: "NetworkAcl Resource Information List"
                    type: array
                    items:
                      $ref: "../model/NetworkAcl.yaml#/definitions/networkAcl"
                  totalCount:
                    description: "Total Number"
                    type: number
              requestId:
                description: "Request ID"
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal error"


    post:
      description: "Create NetworkAcl API"
      operationId: CreateNetworkAcl
      parameters:
        - name: networkAclSpec
          in: body
          required: true
          description: "Create NetworkAcl request parameter"
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/NetworkAclSpec.yaml#/definitions/networkAclSpec"
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              result:
                description: "Returned Results"
                properties:
                  networkAclId:
                    description: "networkAcl ID"
                    type: string
              requestId:
                description: "Request ID"
                type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal error"


  "/networkAcls/{networkAclId}":
    get:
      summary: "Query NetworkAcl information details"
      description: "Query NetworkAcl resource details"
      operationId: describeNetworkAcl
    
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                description: "Returned Results"
                properties:
                  networkAcl:
                    description: "NetworkAcl Resource Information"
                    $ref: "../model/NetworkAcl.yaml#/definitions/networkAcl"
              requestId:
                description: "Request ID"
                type: string
    
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal error"

    
    delete:
      summary: "Delete NetworkAcl"
      description: "Delete NetworkAcl API"
      operationId: deleteNetworkAcl
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                description: "Request ID"
                type: string
        404:
          description: NOT_FOUND
        500:
          description: Internal error
        
    
    patch:
      summary: "Modify NetworkAcl"
      description: "Modify NetworkAcl API"
      operationId: modifyNetworkAcl
      parameters:
        - name: modifyNetworkAclSpec
          in: body
          required: true
          description: "Modify NetworkAcl attribute"
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/ModifyNetworkAclSpec.yaml#/definitions/modifyNetworkAclSpec"
    
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                description: "Request ID"
                type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        500:
          description: "Internal error"


  "/networkAcls/{networkAclId}:associateNetworkAcl":
    post:
      description: "Associate networkAcl API to subnet"
      operationId: associateNetworkAcl
      parameters:
        - name: subnetIds
          in: body
          required: true
          description: "Modify NetworkAcl attribute"
          schema:
            type: array
            items:
              type: string
          
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              requestId:
                description: "Request ID"
                type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        500:
          description: "Internal error"


  "/networkAcls/{networkAclId}:disassociateNetworkAcl":
    post:
      description: "Disassociate NetworkAcl API from subnet"
      operationId: disassociateNetworkAcl
      parameters:
        - name: subnetId
          in: query
          type: string
          required: true
          description: "Subnet ID Disassociated from NetworkAcl"

      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                description: "Request ID"
                type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        500:
          description: "Internal error"


  "/networkAcls/{networkAclId}:addNetworkAclRules":
    post:
      description: "Add NetworkAcl rule API"
      operationId: addNetworkAclRules
      parameters:
        - name: addNetworkAclRulesSpec
          in: body
          required: true
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/AddNetworkAclRulesSpec.yaml#/definitions/addNetworkAclRulesSpec"
      
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              requestId:
                description: "Request ID"
                type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal error"

    
  "/networkAcls/{networkAclId}:removeNetworkAclRules":
    post:
      description: "Remove NetworkAcl rule"
      operationId: removeNetworkAclRules
      parameters:
        - name: ruleIds
          in: body
          required: true
          description: "Modify NetworkAcl attribute"
          schema: 
            type: array
            items:
              type: string
      
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                description: "Request ID"
                type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        500:
          description: "Internal error"


  "/networkAcls/{networkAclId}:modifyNetworkAclRules":
    post:
      description: "Modify NetworkAcl API"
      operationId: modifyNetworkAclRules
      parameters:
        - name: modifyNetworkAclRulesSpec
          in: body
          required: true
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/ModifyNetworkAclRules.yaml#/definitions/modifyNetworkAclRulesSpec"
      
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                 description: "Request ID"
                 type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        500:
          description: "Internal error"


parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  networkAclId:
    name: networkAclId
    in: path
    required: true
    type: string
    description: networkAclId ID