swagger: "2.0"
info:
  version: "v1"
  title: Quota
  description: "Quota APIs"

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/quotas/":
     get:
       summary: "Query quota information"
       description: "Query quota information"
       operationId: DescribeQuota

       parameters:
          - name: type
            in: query
            required: true
            type: string
            description: "Resource Type. Value Range: VPC, elastic_ip, subnet, security_group, VPCpeering, network_interface (quota only sums up secondary network interface)"
          - name: parentResourceId
            in: query
            type: string
            description: "If the type is VPC, elastic_ip, network_interface, do not set; if the type is subnet, security_group, VPCpeering, set as VPCId"

       responses:
         200:
           description: Successful operation
           schema:
             type:  object
             properties:
               result:
                 description: "Returned Results"
                 properties:
                   quota:
                     type: object
                     schema:
                       $ref: "../model/Quota.yaml#/definitions/quota"
               requestId:
                 description: "Request ID"
                 type: string
         400:
           description: "invalid parameter"
         500:
           description: "Internal server error"

     patch:
       summary: "Modify quota information"
       description: "Modify quota information"
       x-jdcloud-internal: true
       operationId: ModifyQuota

       parameters:
          - name: modifyQuotaSpec
            in: body
            required: true
            description: "Modify quota"
            x-jdcloud-tiered: false
            schema:
              $ref: "../model/ModifyQuotaSpec.yaml#/definitions/modifyQuotaSpec"

       responses:
         200:
           description: Successful operation
           schema:
             type:  object
             properties:
               requestId:
                 description: "Request ID"
                 type: string
         400:
           description: "invalid parameter"
         404:
           description: "resource not found"
         500:
           description: "Internal server error"


parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
