swagger: "2.0"
info:
  version: "v1"
  title: Segment
  description: "Segment APIs"

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/segments/":
     #describe segments
    get:
      summary: "Query segment list"
      description: "Query segment list"
      operationId: describeSegments
      x-jdcloud-internal: true
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          minimum: 1
          description: "Page; it is 1 by default. Value Range: [1,∞); when the pages exceed total pages, show the last page"
        - name: pageSize
          in: query
          type: integer
          default: 20
          minimum: 10
          maximum: 100
          description: "Paging Size: 20 by default. Value Range: [10, 100]"
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
                 segmentIds - Segment ID list, support multiple IDs
                 segmentNames - Segment name list, support multiple names
                 provider - IP service provider, values include bgp or no_bgp, cn-north-1: bgp; cn-south-1: [bgp, no_bgp]; cn-east-1: [bgp, no_bgp]; cn-east-2: bgp, support single provider
    
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                description: "Returned Results"
                properties:
                  segments:
                    description: "Segment Resource Information List"
                    type: array
                    items:
                      $ref: "../model/Segment.yaml#/definitions/segment"
                  totalCount:
                    description: "Total Number"
                    type: number
              requestId:
                description: "Request ID"
                type: string

  "/segments/{segmentId}":
      #describe segment
      get:
        summary: "Query segment information details"
        description: "Query segment information details"
        operationId: describeSegment
        x-jdcloud-internal: true
        responses:
          200:
            description: OK
            schema:
              properties:
                result:
                  description: "Returned Results"
                  properties:
                    segment:
                      description: "Segment Resource Information"
                      $ref: "../model/Segment.yaml#/definitions/segment"
                requestId:
                  description: "Request ID"
                  type: string
          400:
            description: "invalid parameter"
          401:
            description: "Authentication failed"

parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  segmentId:
    name: segmentId
    in: path
    required: true
    type: string
    description: "Segment ID"
