swagger: "2.0"
info:
  version: "v1"
  title: Subnet
  description: "Subnet APIs"

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/subnets/":
     #describe subnets
     get:
       summary: "Query subnet list"
       description: "Query subnet list"
       operationId: describeSubnets

       parameters:
          - name: pageNumber
            in: query
            type: integer
            default: 1
            minimum: 1
            description: "Page: 1 by default. Value Range: [1,∞); when the pages exceed total pages, show the last page"
          - name: pageSize
            in: query
            type: integer
            default: 20
            minimum: 10
            maximum: 100
            description: "Paging Size; 20 by default. Value Range: [10, 100]"

          - name: filters
            in: query
            type: array
            items:
              #$ref: "/jcloud-open-api/common/model/Filter.yaml#/definitions/filter"
              $ref: "../../common/model/Filter.yaml#/definitions/filter"
            description: |
                   subnetIds - Subnet ID list, support multiple IDs
                   subnetNames - Subnet name list, support multiple names
                   routeTableId	- Subnet associated route table Id, support single Id
                   aclId - Subnet associated acl Id, support single Id
                   VPCId- VPC ID of subnet, support single Id

       responses:
         200:
           description: OK
           schema:
             properties:
               result:
                 description: "Returned Results"
                 properties:
                   subnets:
                     description: "Subnet Resource Information List"
                     type: array
                     items:
                       $ref: "../model/Subnet.yaml#/definitions/subnet"
                   totalCount:
                     description: "Total Number"
                     type: number
               requestId:
                 description: "Request ID"
                 type: string
  
     post:
       summary: "Create subnet"
       description: "Create subnet"
       operationId: createSubnet
       parameters:
         - name: subnetSpec
           in: body
           required: true
           description: "Apply for creating subnet resource information"
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/SubnetSpec.yaml#/definitions/subnetSpec"
       responses:
         200:
           description: Successful operation
           schema:
             type: object
             properties:
               result:
                 description: "Returned Results"
                 properties:
                   subnetId:
                     description: "Subnet ID"
                     type: string
               requestId:
                 description: "Request ID"
                 type: string
         400:
           description: "Invalid parameter"
         401:
           description: "Authentication failed"
         404:
           description: "Not found"
         409:
           description: "Parameter conflict"
         429:
           description: "Quota exceeded"
         500:
           description: "Internal server error"
         503:
           description: "Service unavailable"

  "/subnets/{subnetId}":
      #describe subnet
      get:
        summary: Query subnet information details
        description: "Query subnet information details"
        operationId: describeSubnet

        responses:
          200:
            description: OK
            schema:
              properties:
                result:
                  description: "Returned Results"
                  properties:
                    subnet:
                      description: "Subnet Resource Information"
                      $ref: "../model/Subnet.yaml#/definitions/subnet"
                requestId:
                  description: "Request ID"
                  type: string

      patch:
        summary: "Modify subnet"
        description: "Modify subnet API"
        operationId: modifySubnet
        parameters:
          - name: modifySubnetSpec
            in: body
            required: true
            description: "Modify subnet"
            x-jdcloud-tiered: false
            schema:
              $ref: "../model/ModifySubnetSpec.yaml#/definitions/modifySubnetSpec"

        responses:
          200:
            description: OK
            schema:
              properties:
                requestId:
                  description: "Request ID"
                  type: string
          400:
            description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
          404:
            description: Resource not found

      delete:
        summary: "Delete subnet"
        description: "Delete subnet"
        operationId: deleteSubnet
        responses:
          200:
            description: OK
            schema:
              properties:
                requestId:
                  description: "Request ID"
                  type: string
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          409:
            description: "Parameter conflict" 
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"


parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  subnetId:
    name: subnetId
    in: path
    required: true
    type: string
    description: Subnet ID
