swagger: "2.0"
info:
  version: "v1"
  title: Resolution Record
  description: "Cloud Resolution OpenAPI Resolution Record API"

basePath: /regions/{regionId}

paths:          
  /domain/{domainId}/RR:
  ###################### Query Resolution Record of Main Domain Name ######################
    get:
      description: "Query the Resolution Record of the main domain name"
      operationId: searchRR
      parameters:
        - name: pageNumber
          in: query
          type: integer
          description: "Current page, starting value is 1, default value is 1"
          required: false
        - name: pageSize
          in: query
          type: integer
          description: "Number of rows per page set during the page query, default value is 10"
          required: false
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  dataList:
                    description: "List of Resolution Records"
                    type: array
                    items:
                      $ref: "../model/RR.yaml#/definitions/RR"
                  totalCount:
                    description: "Number of All Resolution Records"
                    type: integer
                  totalPage:
                    description: "Pages of All Resolution Records"
                    type: integer
                  currentCount:
                    description: "Resolution Records of Current Page"
                    type: integer
              requestId:
                type: string
                description: "ID of This Request"
        400:
          description: BAD_REQUEST
          
  /domain/{domainId}/viewTree:
  ###################### Query All DNS Resolution Lines ######################
    get:
      description: "Query all basic cloud resolution lines"
      operationId: getViewTree
      parameters:
        - name: loadMode
          in: query
          type: integer
          required: false
          description: "Display Mode"
        - name: packId
          in: query
          type: integer
          required: true
          description: "Package ID"
        - name: viewId
          in: query
          type: integer
          required: true
          description: "View ID, 0 by default"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  data:
                    description: "Tree of Resolution Line"
                    type: array
                    items:
                      $ref: "../model/RR.yaml#/definitions/viewTree"
              requestId:
                type: string
                description: "ID of This Request"
        400:
          description: BAD_REQUEST
          
  /domain/{domainId}/RRAdd:
  ###################### Add Resolution Record of Domain Name ######################
    post:
      description: "Add a Resolution Record of the Domain Name"
      operationId: addRR
      parameters:
        - name: req
          in: body
          description: "RR Parameter"
          required: true
          schema:
            $ref: "../model/RR.yaml#/definitions/addRR"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  dataList:
                    description: "Resolution Record Result after Successful Addition"
                    $ref: "../model/RR.yaml#/definitions/RR"
              requestId:
                type: string
                description: "ID of This Request"
        400:
          description: BAD_REQUEST
          
  /domain/{domainId}/RRUpdate:
  ###################### Modify Resolution Record of Domain Name ######################
    post:
      description: "Modify a Resolution Record of the Main Domain Name"
      operationId: updateRR
      parameters:
        - name: req
          in: body
          schema:
            $ref: "../model/RR.yaml#/definitions/updateRR"
          required: true
          description: "UpdateRR Parameter"
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                description: "ID of This Request"
                type: string
        400:
          description: BAD_REQUEST
          
  /domain/{domainId}/RROperate:
  ###################### Operation Set of Domain Name Resolution Record ######################
    post:
      description: "Enable, disable, or delete the resolution records under the main domain name"
      operationId: operateRR
      parameters:
        - name: ids
          in: query
          type: array
          items:
            type: integer
          required: true
          description: "Resolution Record ID of the Operation Required"
        - name: action
          in: query
          type: string
          required: true
          description: "Operation Type, On->Enable, Off->Disable, Del->Delete"
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
                description: "ID of This Request"
        400:
          description: BAD_REQUEST 
         
# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID to which the instance belongs"
  domainId:
    name: domainId
    in: path
    required: true
    type: string
    description: "Domain Name ID"