swagger: "2.0"
definitions:
  backup:
    x-jdcloud-module: redis
    title: backup
    required:
      - baseId
      - backupFileName
      - spaceId
      - backupStartTime
      - backupEndTime
      - backupType
      - backupSize
      - backupStatus
      - backupDownloadURL
    properties:
      baseId:
        type: string
        description: "Backup Operation ID"
      backupFileName:
        type: string
        description: "Name of the Backup File"
      spaceId:
        type: string
        description: "Backup Instance ID"
      backupStartTime:
        type: string
        format: date-time
        description: "Backup Start Time"
      backupEndTime:
        type: string
        format: date-time
        description: "Backup End Time"             
      backupType:
        type: integer
        description: "For backup type, 1 means manual backup, 0 means automatic backup"
      backupSize:
        type: integer
        description: "For the size of backup file, if the instance is a cluster version, it means the sum of the size of each shard backup file"
      backupStatus:
        type: integer
        description: "For the status of backup task, 1 means failure, 2 means success"
      backupDownloadURL:
        type: string
        description: "The URL address of the backup file download, the cluster version has multiple URL addresses"