swagger: "2.0"
definitions:
  configItem:
    x-jdcloud-module: redis
    title: configItem
    type: object
    required: 
      - configName
      - configValue
    properties:
      configName:
        type: string
        description: |
          configName only supports the following parameters currently:
          maxmemory-policy: the maximum limit of memory usage for memory culling strategies
          Hash-max-ziplist-entries: A hash object implemented with ziplist encoding. The maximum number of entries can be stored in the ziplist
          Hash-max-ziplist-value: Hash object is implemented with ziplist encoding, which is the maximum value length that can be stored in the ziplist
          List-max-ziplist-entries: List object is implemented with ziplist encoding, which is the maximum number of entries stored in the ziplist
          List-max-ziplist-value: List object is implemented with ziplist encoding, which is the maximum value length stored in the ziplist
          Set-max-intset-entries: Collection object is implemented by intset encoding, which is the maximum number of entries stored in the intset threshold
          Zset-max-ziplist-entries: An ordered collection object is implemented with ziplist encoding, which is the maximum number of entries stored in the ziplist
          Zset-max-ziplist-value: An ordered collection object is implemented with ziplist encoding, which is the maximum value length stored in the ziplist
          Slowlog-log-slower-than: The unit of log timeout of slow query is microseconds and negative numbers means disable
          Notify-keyspace-events: Event Notification
      configValue:
        type: string
        description: |
          The configuration values ​​of the parameters are as follows:
          maxmemory-policy：[volatile-lru , allkeys-lru , volatile-random , allkeys-random , volatile-ttl , noeviction]
          hash-max-ziplist-entries：[1-10000]
          hash-max-ziplist-value：[1-10000]
          list-max-ziplist-entries：[1-10000]
          list-max-ziplist-value：[1-10000]
          set-max-intset-entries：[1-10000]
          zset-max-ziplist-entries：[1-10000]
          zset-max-ziplist-value：[1-10000]
          slowlog-log-slower-than：[1-10000]
          notify-keyspace-events：[K , E , g , $ , l , s , h , z , x , e , A]

