swagger: "2.0"
definitions:
  instanceClass:
    x-jdcloud-module: redis
    description: "Information of a JCS for Redis Instance Type"
    type: object
    properties:
      instanceClass:
        type: string
        description: "For instance type code, see instance type code table"
      cpu:
        type: integer
        description: cpu
      memoryMB:
        type: integer
        description: "Memory"
      diskGB:
        type: integer
        description: "Disk"
      maxConnetction:
        type: integer
        description: "Maximum Number of Links"
      bandwidthMbps:
        type: integer
        description: "Bandwidth"
      