swagger: "2.0"
info:
  version: "v1"
  title: Snapshot APIs
  description: "Snapshot APIs provides functions such as creating snapshots, querying snapshot information, deleting snapshots, and modifying snapshot information."

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/snapshots":
   ###################### API for Cloud Disk Snapshot List Query ######################
    get:
      operationId: describeSnapshots
      summary: "Query cloud disk snapshot list"
      description: "Query the list of cloud disk snapshots. Filters, between multiple filter conditions is logic AND, and multiple values ​​inside each condition is logic OR"
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          minimum: 1
          description: "Page Number: 1 by default; value range: [1, ∞)"
 
        - name: pageSize
          in: query
          type: integer
          default: 20
          minimum: 10
          maximum: 100
          description: "Paging Size: 20 by default. Value Range: [10, 100]"

        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
            snapshotId - Cloud Disk Snapshot ID, support multiple
            diskId - the Cloud Disk ID of the snapshot to be generated, support multiple
            status - Snapshot status, accurate match, support multiple, value: creating, available, in-use, deleting, error_create or error_delete
            name - Snapshot Name, fuzzy match, support single
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                type: object
                description: "Query Result Set"
                properties:
                  snapshots:
                    type: array
                    description: "List of Snapshot Details Queried"
                    items:
                      $ref: "../model/Snapshot.yaml#/definitions/snapshot"
                  totalCount:
                    type: integer
                    description: "Number of Snapshots Queried"
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

   ###################### API for Cloud Disk Snapshot Creation ######################
    post:
      summary: "Create a cloud disk snapshot"
      description: |
        -   Create a snapshot for the specified cloud disk, and the status of the newly generated snapshot is creating.
        -   The quota for single-user snapshots in the same region is 15.
        -   To ensure data integrity, please stop writing to the cloud disk before creating a snapshot to ensure the integrity of snapshot data.
        -   Before creating a snapshot, we suggest you detach the cloud disk and reattach the disk to the virtual machine after the snapshot is created.
        -   The life cycle of manual snapshots is independent from the cloud disk. Please delete unnecessary snapshots in time.
        -   The time demanded to create a snapshot depends on the capacity of the cloud disk. The larger the capacity is, the longer it will take.
      operationId: createSnapshot
      parameters:
        - name: SnapshotSpec
          in: body
          required: true
          description: "snapshot specification"
          schema:
            $ref: "../model/SnapshotSpec.yaml#/definitions/snapshotSpec"
        - name: clientToken
          in: query
          required: true
          type: string
          description: "Idempotence Check Parameter"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                description: "Result Set"
                properties:
                  snapshotId:
                    description: "ID of the Created Snapshot"
                    type: string
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

   ###################### API for Querying Details of Cloud Disk Snapshot ######################
  "/snapshots/{snapshotId}":
      get:
        summary: "Cloud Disk Snapshot Details"
        description: "Query cloud disk snapshot details"
        operationId: describeSnapshot
        responses:
          200:
            description: OK
            schema:
              properties:
                result:
                  description: "Cloud Disk Snapshot Details Queried"
                  type: object
                  properties:
                    snapshot:
                      $ref: "../model/Snapshot.yaml#/definitions/snapshot"
                requestId:
                  type: string
                  description: "Request ID"
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

   ###################### API for Cloud Disk Snapshot Deletion ######################
      delete:
        summary: "Delete a cloud disk snapshot"
        description: |
          -   Delete a single cloud disk snapshot: The snapshot status must be in available or error status.
          -   The snapshot is independent from life cycle of the cloud disk. Deleting a snapshot does not have any effect on the cloud disk that created the snapshot.
          -   After the snapshot is deleted, it cannot be recovered. Please be cautious.
        operationId: deleteSnapshot
        responses:
          200:
            description: OK
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

   ###################### API for Snapshot Properties Modification ######################
      patch:
        summary: "Modify snapshot properties"
        description: "Modify the name or description of the snapshot"
        operationId: modifySnpAttribute
        parameters:
          - name: name
            in: query
            type: string
            description: "Snapshot Name"
          - name: description
            in: query
            type: string
            description: "Snapshot Description. Name or description must be specified"
        responses:
          200:
            description: OK
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID"
  snapshotId:
    name: snapshotId
    in: path
    required: true
    type: string
    description: "Snapshot ID"
        

    
