swagger: "2.0"
definitions:
  addNetworkAclRulesSpec:
    x-jdcloud-module: vpc
    required:
      - networkAclRuleSpecs
    properties:
      networkAclRuleSpecs:
        type: array
        items:
          $ref: "./AddNetworkAclRuleSpec.yaml#/definitions/addNetworkAclRuleSpec"
        description: "NetworkAcl Rule List"