swagger: "2.0"
definitions:
  addRouteTableRules:
    x-jdcloud-module: vpc
    required:
      - nextHopType
      - nextHopId
      - addressPrefix
    properties:
      nextHopType:
        type: string
        description: "Type of Next. Value Range: instance: Virtual Machine, internet: public network, VPC_peering: VPC peering connection, bgw: border gateway"
      nextHopId:
         type: string
         description: "Next ID"
      addressPrefix:
        type: string
        description: "Prefix of matching address, addressPrefix of internet type route and other types of routes is not allowed to be duplicate"
      priority:
         type: number
         description: "Rule Matching Priority. Value Range: [1,255], default value is 100. When routing rule subnet masks are different, the longest routing will match the priority; when routing rule subnet masks are the same, forwarding is based on priority matching, where the smaller the priority number is, the higher priority it is; when the routing rule subnet masks and the priority are the same but the next is different, the equal-cost routing is constituted and the load of next is balanced."

