swagger: "2.0"
definitions:
  assignSecondaryIpsSpec:
    x-jdcloud-module: vpc
    properties:
        force:
          type: boolean
          description: "When secondary ip is occupied by other interfaces, whether to preempt it or not. false: non-preemption for reallocation, true: preemption for reallocation, default preemption for reallocation. Default value: true"
          default: true
        secondaryIps:
          type: array
          items:
            type: string
          description: "Assign Allocated Secondary IP Address"
        secondaryIpCount:
          type: number
          description: "Assign Automatically Allocated Number of Secondary IP"
