swagger: "2.0"
definitions:
  associateElasticIpSpec:
    x-jdcloud-module: vpc
    properties:
      elasticIpId:
        type: string
        description: "Associated Elastic IP ID"
      privateIpAddress:
        type: string
        description: "Associate Elastic IP to Assigned Private IP"
      elasticIpAddress:
        type: string
        description: "Associated Elastic IP Address"
