swagger: "2.0"
definitions:
  createVpcPeeringSpec:
    x-jdcloud-module: vpc
    required:
      - vpcPeeringName
      - vpcId
      - remoteVpcId
    properties:
      vpcPeeringName:
        type: string
        description: "VPCPeering Name, Must Provide A nName. Value Range of Name: 1-32 Chinese, English capital and lowercase letters, numbers and underline delimiter"
      vpcId:
        type: string
        description: "VPCPeering Home Terminal VPC ID"
      remoteVpcId:
        type: string
        description: "VPCPeering Opposite Terminal VPC ID"
      description:
        type: string
        description: "VPCPeering Description. Value Range: 0-256 Chinese, English capital and lowercase letters, numbers and underline delimiter"
