swagger: "2.0"
definitions:
  disassociateRouteTableSpec:
    x-jdcloud-module: vpc
    required:
      - subnetId
    properties:
      subnetId:
        type: string
        description: "Subnet ID to be disassociated by route table, subnet associates the default route table upon disassociation"



