swagger: "2.0"
definitions:
  elasticIpSpec:
    x-jdcloud-module: vpc
    required:
      - bandwidthMbps
      - provider
    properties:
      bandwidthMbps:
        type: integer
        description: "Elastic IP Speed lLimit (unit: Mbps). Value Range: [1-200]"
      provider:
        type: string
        #todo: define common enums for referrence
        enum:
          - "BGP"
          - "NO_BGP"
        description: "IP service provider, values include bgp or no_bgp, cn-north-1: bgp; cn-south-1: [bgp, no_bgp]; cn-east-1: [bgp, no_bgp]; cn-east-2: bgp"
      chargeSpec:
        #$ref: "/jcloud-open-api/charge/model/ChargeSpec.yaml#/definitions/chargeSpec"
        $ref: "../../charge/model/ChargeSpec.yaml#/definitions/chargeSpec"
        description: "Billing Configuration"
