swagger: "2.0"
definitions:
  modifyNetworkInterfaceSpec:
    x-jdcloud-module: vpc
    properties:
      networkInterfaceName:
        type: string
        description: "Elastic Network Interface name, only allows Chinese, numbers, capital and lowercase letters, English underline “_” and line-through “-”, must provide a name which cannot exceed 32 characters"
      description:
        type: string
        description: "Description, allow all characters under UTF-8 coding, not exceeding 256 characters"
      securityGroups:
        type: array
        items:
          type: string
        description: "To replace the Security Group with mode update of the original Security Group. If the Security Group ID list is updated, a maximum of 5 Security Groups can be done"

