swagger: "2.0"
definitions:
  modifyVpcSpec:
    x-jdcloud-module: vpc
    properties:
      vpcName:
        type: string
        description: "VPC name, only allow Chinese, numbers, capital and lowercase letters, English underline “_” and line-through “-”, must provide a name which cannot exceed 32 characters."
      description:
        type: string
        description: "VPC description, allow all characters under UTF-8 coding, which cannot exceed 256 characters."


