swagger: "2.0"
definitions:
  modifyRouteTableSpec:
    x-jdcloud-module: vpc
    properties:
      routeTableName:
        type: string
        description: "Route Table Name Value Range: 1-32 Chinese, English capital and lowercase letters, numbers and underline delimiter"
      description:
        type: string
        description: "Route Table Description. Value Range: 0-256 of all characters entered under UTF-8 coding"
