swagger: "2.0"
definitions:
  networkAclSpec:
    x-jdcloud-module: vpc
    required:
      - vpcId
      - networkAclName
    properties:
      vpcId:
        type: string
        description: "VPC ID"
      networkAclName:
        type: string
        description: "NetworkAcl Name"
      description:
        type: string
        description: "Description, allow all characters under UTF-8 coding, not exceeding 256 characters"