swagger: "2.0"
definitions:
  networkSecurityGroup:
    x-jdcloud-module: vpc

    properties:
      networkSecurityGroupId:
        type: string
        description: "Security Group ID"
      networkSecurityGroupName:
        type: string
        description: "Security Group Name"
      description:
        type: string
        description: "Security Group Description Information"
      vpcId:
        type: string
        description: "VPC ID of Security Group"

      securityGroupRules:
        type: array
        items:
         $ref: "./SecurityGroupRule.yaml#/definitions/securityGroupRule"
        description: "Security Group Rule Information"

      createdTime:
        type: string
        description: "Creation Time of Security Group"

