swagger: "2.0"
definitions:
  networkAcl:
    x-jdcloud-module: vpc
    properties:
      networkAclId:
        type: string
        description: networkAcl ID
      networkAclName:
        type: string
        description: "NetworkAcl Name"
      vpcId:
        type: string
        description: "VPC ID"
      networkAclRules:
        type: array
        description: "NetworkAcl Rule List"
        items:
          $ref: "./NetworkAclRule.yaml#/definitions/networkAclRule"
      subnetIds:
        type: array
        items:
          type: string
        description: "NetworkAcl Associated Subnet List"
      description:
        type: string
        description: "Description, allow all characters under UTF-8 coding, not exceeding 256 characters"
      createdTime:
        type: string
        description: "NetworkAcl Creation Time"