swagger: "2.0"
definitions:
  networkSecurityGroupSpec:
    x-jdcloud-module: vpc
    required:
      - vpcId
      - networkSecurityGroupName
    properties:
      vpcId:
        type: string
        description: "VPC ID"
      networkSecurityGroupName:
        type: string
        description: "Security Group name, only allows Chinese, numbers, capital and lowercase letters, English underline '_' and line-through '-', must provide a name which cannot exceed 32 characters."
      description:
        type: string
        description: "Description, allow all characters under UTF-8 coding, which cannot exceed 256 characters"
