swagger: "2.0"
definitions:
  quota:
    x-jdcloud-module: vpc

    properties:
      type:
        type: string
        description: "Resource Type. Value Range: VPC, elastic_ip, subnet, security_group, VPCpeering, network_interface (quota only sums up secondary network interface)"
      parentResourceId:
        type: string
        description: "VPC, elastic_ip and network_interface are blank; subnet, security_group and VPCpeering are VPCId"
      maxLimit:
        type: number
        description: "Quota Size"
      count:
        type: number
        description: "Number of Existing Resources"
