swagger: "2.0"
definitions:
  subnetSpec:
    x-jdcloud-module: vpc
    required:
      - vpcId
      - subnetName
      - addressPrefix
    properties:
      vpcId:
        type: string
        description: "VPC ID of Subnet"
      subnetName:
        type: string
        description: "Subnet name, only allow Chinese, numbers, capital and lowercase letters, English underline “_” and line-through “-”, must provide a name which cannot exceed 32 characters."
      addressPrefix:
        type: string
        description: "Subnet Segment, Subnet Segment in VPC Cannot Overlap. Value Range of cidr: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 and their subnets included and the length of subnet mask is between 16 and 28. If VPC includes cidr, it must be the cidr subnet of VPC"
      routeTableId:
        type: string
        description: "Subnet associated route table Id, it is default route table of VPC by default"
      description:
        type: string
        description: "Subnet description information, allow all characters under UTF-8 coding, which cannot exceed 256 characters."

