swagger: "2.0"
definitions:
  vpcPeering:
    x-jdcloud-module: vpc
    properties:
      vpcPeeringId:
        type: string
        description: "VPCPeering ID"
      vpcPeeringName:
        type: string
        description: "VPCPeering name, no duplicate under the same account is allowed. Value Range: 1-32 Chinese, English capital and lowercase letters, numbers and underline delimiter"
      vpcPeeringState:
        type: string
        description: "Status, values include Connected, Disconnected, Initiated"
      description:
        type: string
        description: "VPCPeering description, can be null. Value Range: 0-256 Chinese, English capital and lowercase letters, numbers and underline delimiter"
      vpcInfo:
        $ref: "./VpcPeeringVpcInfo.yaml#/definitions/vpcPeeringVpcInfo"
        description: "VPC Information Launching VPCPeering"
      remoteVpcInfo:
        $ref: "./VpcPeeringVpcInfo.yaml#/definitions/vpcPeeringVpcInfo"
        description: "Opposite Terminal VPC information"
      createdTime:
        type: string
        description: "VPCPeering Creation Time"

