swagger: "2.0"
definitions:
  vpcPeeringVpcInfo:
    x-jdcloud-module: vpc
    properties:
      vpcId:
        type: string
        description: "VPC ID of Subnet"
      vpcName:
        type: string
        description: "VPC Name. Value Range: 1-60 Chinese, English capital and lowercase letters, numbers and underline delimiter"
      addressPrefix:
        type: array
        items:
          type: string
        description: "If it is blank, segment is not limited; if it is not blank, it is 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 and their subnets included and the length of subnet mask is between 16 and 28"

