swagger: "2.0"
definitions:
  vpcSpec:
    x-jdcloud-module: vpc
    required:
      - vpcName
    properties:
      vpcName:
        type: string
        description: "VPC name, only allow Chinese, numbers, capital and lowercase letters, English underline “_” and line-through “-”, must provide a name which cannot exceed 32 characters."
      addressPrefix:
        type: string
        description: "If it is blank, segment is not limited; if it is not blank, it is 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 and their subnets included and the length of subnet mask is between 16 and 28"
      description:
        type: string
        description: "VPC description, allow all characters under UTF-8 coding, which cannot exceed 256 characters."


