swagger: "2.0"
definitions:
  dataPoint:
    x-jdcloud-module: monitor
    type: object
    properties:
      timestamp:
        type: integer
        format: int64
        description: "Time Stamp"
      value:
        type: string
        description: "Value"        