swagger: "2.0"
definitions:
  metricDataCm:
    x-jdcloud-module: monitor
    required:
      - namespace
      - metric
      - dimensions
      - timestamp
      - type
      - values
    type: object
    properties:
      namespace:
        type: string
        description: "Naming space, no more than 255 bytes in length, only English, numbers, underlines_, dot., [0-9][a-z] [A-Z] [. _ ] are allowed, others will return err"
      metric:
        description: "Metric name, no more than 255 bytes in length, only English, numbers, underlines_, dot., [0-9][a-z] [A-Z] [. _ ] are allowed, others will return err"
        type: string
      dimensions:
        type: object
        description: "Data dimension, data type is map type, support at least one, up to five tags, no more than 255 bytes in total length, only English, numbers, underlines_, dot., [0-9][a-z] [A-Z] [. _ ] are allowed, others will return err"
        additionalProperties:
          type: string
      timestamp:
        type: integer
        required: true
        format: int64
        description: "Timestamp for reporting data points only supports 10-bit, second timestamp, the time of the past 30 days cannot be written in"
        required: true
      type:
        type: integer
        required: true
        description: "Data reporting type, 1 is the original value, 2 is aggregated data. When the aggregated data is reported, it is suggested that it shall be reported during the period of 60s, otherwise, it cannot be queried normally."
      values:
        type: object
        description: "Metric value collection, the data type must be the map type, key is the data type, value is the data value, when type=1, key only can be “value”, the reported is the original value, when type=2, key can be “avg”, “sum”, “last”, “max”, “min”, “count”, which only support the above types, otherwise it will report an error, value contents are integers or floating point numbers, the largest value is 9223372036854775807, count only supports numbers >=0"
        additionalProperties:
          type: string