swagger: "2.0"
definitions:
  tagFilter:
    type: object
    x-jdcloud-module: monitor
    required:
      - key
      - values
    properties:
      key:
        description: "Tag Key"
        type: string
      values:
        description: "Tag Value"
        type: array
        items:
          type: string
