swagger: "2.0"
info:
  version: "v1"
  title: JD Cloud Resolution OpenAPI APIs
  description: "JD Cloud Resolution OpenAPI APIs"
host: "clouddnsservice.jdcloud-api.com"
x-jdcloud-version: "v1"
x-jdcloud-revision: "1.0.3"