swagger: "2.0"
definitions:
  chargeSpec:
    x-jdcloud-module: charge
    properties:
      chargeMode:
        type: string
        enum:
          - prepaid_by_duration
          - postpaid_by_usage
          - postpaid_by_duration
        default: postpaid_by_duration
        description: "Billing model value is prepaid_by_duration, postpaid_by_usage or postpaid_by_duration; prepaid_by_duration means Pay-In-Advance, postpaid_by_usage means Pay-As-You-Go By Consumption and postpaid_by_duration means pay by configuration; is postpaid_by_duration by default. Please refer to the Help Documentation of specific product line to confirm the billing type supported by the production line"
      chargeUnit:
        type: string
        enum:
          - month
          - year
        description: "Billing unit of Pay-In-Advance, the Pay-In-Advance is compulsory, and valid only when chargeMode is prepaid_by_duration, and the value is month or year and month by default"
      chargeDuration:
        type: integer
        description: "Pay-In-Advance billing duration, the Pay-In-Advance is compulsory and valid only when the value of chargeMode is prepaid_by_duration. When chargeUnit is month, the value shall be 1~9; when chargeUnit is year, the value shall be 1, 2 or 3"
