swagger: "2.0"
definitions:
  charge:
    x-jdcloud-module: charge
    properties:
      chargeMode:
        type: string
        enum:
        - prepaid_by_duration
        - postpaid_by_usage
        - postpaid_by_duration
        default: postpaid_by_duration
        description: "Payment Model, the value shall be prepaid_by_duration, postpaid_by_usage or postpaid_by_duration; prepaid_by_duration refers to Pay-In-Advance; postpaid_by_usage refers to Pay By Consumption and Pay-As-You-Go; postpaid_by_duration refers to Pay By Configuration and Pay-As-You-Go, and is postpaid_by_duration by default"
      chargeStatus:
        type: string
        enum:
        - normal
        - overdue
        - arrear
        - overdue
        description: "Cost Payment Status, the value is respectively normal, overdue and arrear."
      chargeStartTime:
        type: string
        description: "The start time of the billing shall be subject to ISO8601, with the UTC time used in the format of YYYY-MM-DDTHH:mm:ssZ"
      chargeExpiredTime:
        type: string
        description: "Expiration Time, i.e. the expiration time of Pay-In-Advance resource, which shall be subject to ISO8601, with the UTC time used in the format of YYYY-MM-DDTHH:mm:ssZ. Pay-As-You-Go resource field is blank."
      chargeRetireTime:
        type: string
        description: "The Expected Release Time refers to the expected release time of resources. This value is both available for the Pay-In-Advance/Pay-As-You-Go resources, conforming to the ISO8601 standard, with the UTC time used in the format of YYYY-MM-DDTHH:mm:ssZ"