swagger: "2.0"                                 
info:
  version: v1
  title: Backup Management
  description: API related to Relational MONGODB Service

basePath: /regions/{regionId}

paths:
  "/backups": #Create Backup
    post:
      description: "Create Backup"
      operationId: createBackup
      parameters:
        - name: createBackup
          in: body
          description:
          schema:
            type: object
            required:
              - instanceId
            properties:
              instanceId:
                type: string
                description: "Instance ID"
              backupName:
                type: string
                description: "Backup Name"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  backupId:
                    type: string
              requestId:
                type: string

    get:
      description: "View Backup"
      operationId: describeBackups
      parameters:
        - name: pageNumber
          in: query
          type: integer
          description: "Page Number; Default: 1; Value range: [1, ∞)"
        - name: pageSize
          in: query
          type: integer
          description: "Page Size; Default: 10; Value range: [1,100]"
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: | 
            instanceId - Instance ID, Accurate Matching
            backupId - Backup ID, Accurate Matching
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  backups:
                    type: array
                    items:
                      $ref: ../model/Backup.yaml#/definitions/Backup
                  totalCount:
                    type: integer
                  pageNumber:
                    type: integer
              requestId:
                type: string

  "/backups/{backupId}":
    delete:
      description: "Delete Backup"
      operationId: deleteBackup
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
  
  "/backups/{backupId}/downloadURL":
    get:
      description: "Get Backup Download Link"
      operationId: backupDownloadURL
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                $ref: "../model/BackupDownloadURL.yaml#/definitions/BackupDownloadURL"
              requestId:
                type: string

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  backupId:
    name: backupId
    in: path
    required: true
    type: string
    description: backup ID



