swagger: "2.0"
info:
  version: "v1"
  title: Cross-region Backup Management
  description: API related to Relational MONGODB Service

basePath: /regions/{regionId}

paths:
  "/backupSynchronicities": #Cross-region Backup Synchronization Service
    post:
      description: "Create Cross-region Backup Synchronization Service"
      operationId: createBackupSynchronicity
      x-jdcloud-internal: true
      parameters:
        - name: createBackupSynchronicity
          in: body
          description:
          schema:
            type: object
            required:
              - instanceId
              - srcRegion
              - dstRegion
            properties:
              instanceId:
                type: string
                description: "Source Instance ID"
              srcRegion:
                type: string
                description: "Source Instance Location"
              dstRegion:
                type: string
                description: "Target Zone for Backup Synchronization"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  serviceId:
                    type: string
              requestId:
                type: string

    get:
      description: "Query Cross-region Backup Synchronization Service"
      operationId: describeBackupSynchronicities
      x-jdcloud-internal: true
      parameters:
        - name: pageNumber
          in: query
          type: integer
          description: "Page Number; Default: 1; Value range: [1, ∞)"
        - name: pageSize
          in: query
          type: integer
          description: "Page Size; Default: 10; Value range: [1,100]"
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description:
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  backupSynchronicities:
                    type: array
                    items:
                      $ref: "../model/BackupSynchronicity.yaml#/definitions/BackupSynchronicity"
                  totalCount:
                    type: integer
                  pageNumber:
                    type: integer
              requestId:
                type: string

  "/backupSynchronicities/{serviceId}": #Delete a Cross-region Backup Synchronization Service
    delete:
      description: "Delete Cross-region Backup Synchronization Service"
      operationId: deleteBackupSynchronicities
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  serviceId:
                    type: string
              requestId:
                type: string

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  serviceId:
    name: serviceId
    in: path
    required: true
    type: string
    description: service ID


