swagger: "2.0"
info:
  version: "v1"
  title: Security Management
  description: API related to MONGODB security

basePath: /regions/{regionId}

paths:
  "/instances/{instanceId}/securityIps":
    ###################### Modify Instance Access White List ######################
    post:
      description: "Modify instance access White List"
      operationId: modifySecurityIps 
      parameters:
        - name: modifySecurityIps
          in: body
          description:
          schema:
            type: object
            required:
              - modifyMode
              - securityIps
            properties:
              modifyMode:
                type: string
                description: "Modification Method, Add adds White List, Delete deletes White List."
              securityIps:
                type: string
                description: "IP list under the IP White List group, up to 45 separated by commas, in the following format: 0.0.0.0/0, 10.23.12.24 (IP), or 10.23.12.24/24 (CIDR mode, classless inter-domain routing, /24 indicates the length of the prefix in the address; range [1, 32])."
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string

    get:
      description: "Query Instance Access White List"
      operationId: describeSecurityIps 
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  securityIps:
                    type: string
            requestId:
                type: string
  
# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  instance:
    name: instanceId
    in: path
    required: true
    type: string
    description: Instance ID
