swagger: "2.0"
info:
  version: "v1"
  title: Sensitive Operation Configuration
  description: "Operate the APIs of sensitive operation configuration"

basePath: /regions/{regionId}

paths:
  "/sensitiveOpSetting":
    ###################### Obtain the settings information of Operation Protection ######################
    get:
      description: "Obtain the settings information of Operation Protection"
      operationId: getSensitiveOpSetting
      x-jdcloud-internal: false
      parameters:
       - name: action
         in: query
         type: string
         required: true
         description: "Operate action serviceName:actionName"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  status:
                    type: integer
                    description: "Enabling status of Operation Protection: 0-not enabled, 1-enabled"
                  type:
                    type: integer
                    description: "Verification methods of Operation Protection: 0-none, 1-SMS, 2-email, 3-MFA"
                  extInfo:
                    type: string
                    description: "Expansion information is the mobile number after the mask when type=1, and is the email address after the mask when type=2"
              requestId:
                type: string

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID