swagger: "2.0"
definitions:
  Backup:
    x-jdcloud-module: mongodb
    title: Backup
    type: object
    properties:
      backupId:
        type: string
        description: "Backup ID"
      backupName:
        type: string
        description: "Backup Name"
      instanceId:
        type: string
        description: "Backup Instance ID"
      backupStatus:
        type: string
        description: "Backup Status, Waiting (Waiting), Running (Backing-up), Finished (Finished), Failed (Error)"
      backupStartTime:
        type: string
        description: "Backup Start Time"
      backupEndTime:
        type: string
        description: "Backup End Time"
      backupMode:
        type: string
        description: "Backup Mode, Automated (System Automatic Backup), Manual (Manual Backup)"
      backupSizeByte:
        type: integer
        description: "Size of Whole Backup Set, Unit: Byte"
      