swagger: "2.0"
definitions:
  BackupSynchronicity:
    x-jdcloud-module: mongodb
    title: BackupSynchronicity
    type: object
    properties:
      serviceId:
        type: string
        description: "Cross-region Backup Synchronization Service ID"
      instanceId:
        type: string
        description: "MongoDB Instance ID"
      instanceName:
        type: string
        description: "MongoDB Instance Name"
      serviceStatus:
        type: string
        description: "Cross-region Backup Synchronization Service Status, Normal: running; Error: error"
      srcRegion:
        type: string
        description: "Source Instance Location"
      dstRegion:
        type: string
        description: "Destination Domain of Cross-region Backup Synchronization Service"
      engine:
        type: string
        description: "Database Type"
      engineVersion:
        type: string
        description: "Database Version"
      createTime:
        type: string
        description: "Creation Time"
      newestDataTime:
        type: string
        description: "Latest Data Time Point of Cross-region Backup"

