swagger: "2.0"
definitions:
  BackupDownloadURL:
    x-jdcloud-module: mongodb
    title: BackupDownloadURL
    type: object
    properties:
      backupName:
        type: string
        description: "Backup Name"
      backupInternetDownloadURL:
        type: string
        description: "Address of Public Network Download Link"
      backupIntranetDownloadURL:
        type: string
        description: "Address of Intranet Download Link"
      linkExpiredTime:
        type: string
        description: "Expiration Time of Public Network and Intranet Download Link"
      