swagger: "2.0"
definitions:
  DBInstance:
    x-jdcloud-module: mongodb
    title: DBInstance
    type: object
    properties:
      instanceId:
        type: string
        description: "Instance ID"
      instanceName:
        type: string
        description: "Instance Name"
      engine:
        type: string
        description: "Database Type"
      engineVersion:
        type: string
        description: "Database Version"
      instanceClass:
        type: string
        description: "Instance Type Code"
      instanceStorageGB:
        type: integer
        description: "Storage Space"
      instanceCPU:
        type: integer
        description: "Number of CPU Cores"
      instanceMemoryGB:
        type: integer
        description: "Memory, Unit: GB"
      azId:
        type: array
        items:
          type: string
        description: "AZ ID, AZs at primary, secondary and hidden nodes in turn."
      vpcId:
        type: string
        description: VPCID
      subnetId:
        type: string
        description: "Subnet ID"
      replicaSetName:
        type: string
        description: "Name of Replica Set"
      instanceDomain:
        type: string
        description: "Domain Name"
      DBName:
        type: string
        description: "Default Database Name"
      accountName:
        type: string
        description: "Default User Name"
      instancePort:
        type: string
        description: "Application Access Port"
      instanceStatus:
        type: string
        description: "Instance Status. RUNNING: Running, ERROR: Error, BUILDING: Creating, DELETING: Deleting, RESTORING: Restoring, RESIZING: under Configuration Change"
      backupRetentionPeriod:
        type: integer
        description: "Automatic Backup Retention Time"
      createTime:
        type: string
        description: "Creation Time"
      preferredBackupWindow:
        type: string
        description: "Automatic Backup Time, for example: 00:00-02:00, indicating automatic backup of the database from 0 to 2"
      preferredmaintenanceWindow:
        type: string
        description: "System Maintenance Time, for example: 00:00-02:00, indicating system maintenance from 0 to 2"
      charge:
        $ref: "../../charge/model/Charge.yaml#/definitions/charge"
        description: "Billing Information"
      isSetSecurityIps:
        type: boolean
        description: "Whether to set White List, true: set, false: not set"
