swagger: "2.0"
definitions:
  Flavor:
    x-jdcloud-module: mongodb
    title: Flavor
    type: object
    properties:
      cpu:
        type: integer
        description: "Number of CPU Cores"
      memory:
        type: integer
        description: "Memory, Unit: GB"
      iops:
        type: integer
        description: iops
      maxLink:
        type: integer
        description: "Maximum Connections"
      maxDisk:
        type: integer
        description: "Maximum Number of Disks, Unit: GB"
      minDisk:
        type: integer
        description: "Minimum Number of Disks, Unit: GB"
      diskStep:
        type: integer
        description: "Disk Step Size"
      