swagger: "2.0"
definitions:
  TopologyPair:
    x-jdcloud-module: mongodb
    title: TopologyPair
    type: object
    properties:
      domain:
        type: string
        description: "Domain Name"
      ip:
        type: string
        description: "ip Address"
      port:
        type: string
        description: "Port"
      