swagger: "2.0"
definitions:
  domain:
    type: object
    x-jdcloud-module: clouddnsservice
    properties:
      id:
        type: integer
        description: "Unique ID of the Domain Name"
      domainName:
        type: string
        description: "Domain Name String"
      createTime:
        type: integer
        description: "Creation Time, Format Unix Timestamp " 
      expirationDate:
        type: integer
        description: "Expiration Time, Format Unix Timestamp"
      packId:
        type: integer
        description: "Package Type, 0->Free 1->Enterprise Edition 2->Advanced Edition"