swagger: "2.0"
definitions:
  updateMonitor:
    type: object
    x-jdcloud-module: clouddnsservice
    properties:
      alarmLimit:
        type: integer
        required: true
        description: "Trigger an alarm several times"
      Id:
        type: integer
        required: true
        description: "Monitor Item ID"
      ipBackup01:
        type: string
        required: true
        description: "Alternate Address 1"
      ipBackup02:
        type: string
        required: true
        description: "Alternate Address 2"
      monitorEnable:
        type: integer
        required: true
        description: "Monitoring Status  Turn on monitor 2, Suspend monitor 4"
      monitorFreq:
        type: integer
        required: true
        description: "Monitoring Frequency  Unit: Second"
      monitorPort:
        type: integer
        required: true
        description: "Monitoring Port"
      monitorRule:
        type: integer
        required: true
        description: "Do not modify any 0, forcibly suspend Resolution Record 1 to switch to Alternate Address 2 automatically"
      monitorUri:
        type: string
        required: true
        description: "Monitoring Path"
      notifyEmailEnable:
        type: integer
        required: true
        description: "Do not send mail 0, send mail 1"
      notifyMsgBarEnable:
        type: integer
        required: true
        description: "Do not send notification bar 0, send notification bar 1"
      notifySmsEnable:
        type: integer
        required: true
        description: "Do not send SMS 0, send SMS 1"
      protocol:
        type: integer
        required: true
        description: https 0，https 1
      stopRecoverRule:
        type: integer
        required: true
        description: "0 Automatic Recovery, 1 Manual Recovery"
      switchRecoverRule:
        type: integer
        required: true
        description: "0 Restore to the main host automatically, 1 Restore to the main host manually"
  monitor:
    type: object
    x-jdcloud-module: clouddnsservice
    properties:
      alarmLimit:
        type: integer
        description: "Trigger an alarm several times"
      canRecover:
        type: boolean
        description: "Is it possible to recover now?"
      canSwitch:
        type: boolean
        description: "Is it possible to switch now?"
      clusters:
        type: string
        description: "Collection of machine room probe points"
      domainName:
        type: string
        description: "Main Domain Name"
      hostStatus:
        type: integer
        description: "Machine Status, 0 Normal, 1 Exception"
      hostValue:
        type: string
        description: "Monitoring Object"
      Id:
        type: integer
        description: "Monitor Item ID"
      ipBackup01:
        type: string
        description: "Alternate Address 1"
      ipBackup01Status:
        type: integer
        description: "Status of Alternate Address 1, 0 Normal, 1 Exception"
      ipBackup01Type:
        type: integer
        description: "Type of Alternate Address 1, 1 ip, 2 Domain name"
      ipBackup02: 
        type: string
        description: "Alternate Address 2"
      ipBackup02Status:
        type: integer
        description: "Status of Alternate Address 2, 0 Normal, 1 Exception"
      ipBackup02Type:
        type: integer
        description: "Type of Alternate Address 1, 1 ip, 2 Domain name"
      manualBackup:
        type: string
        description: "Manually Switched Address"
      manualBackupStatus:
        type: integer
        description: "Status of Manually Switched Address, 0 Normal, 1 Exception"
      manualBackupType:
        type: integer
        description: "Type of  Manually Switched Address, 1 ip, 2 Domain name"
      monitorEnable:
        type: integer
        description: "Monitoring Status  Turn on monitor 2, Suspend monitor 4"
      monitorFreq:
        type: integer
        description: "Monitoring Frequency, Unit: s"
      monitorPort:
        type: integer
        description: "Monitoring Port"
      monitorRule:
        type: integer
        description: "Do not modify any 0, forcibly suspend Resolution Record 1 to switch to Alternate Address 2 automatically"
      monitorUri:
        type: string
        description: "Monitoring Path"
      notifyEmail:
        type: string
        description: "Email Address " 
      notifyEmailEnable:
        type: integer
        description: "Do not send mail 0, send mail 1"
      notifyMsgBarEnable:
        type: integer
        description: "Do not send notification bar 0, send notification bar 1"
      notifySms:
        type: string
        description: "Mobile Number"
      notifySmsEnable:
        type: integer
        description: "Do not send SMS 0, send SMS 1"
      protocol:
        type: integer
        description: https 0，https 1
      stopRecoverRule:
        type: integer
        description: "0 Automatic Recovery, 1 Manual Recovery"
      subDomainName:
        type: string
        description: "Subdomain"
      switchRecoverRule:
        type: integer
        description: "0 Restore to the main host automatically, 1 Restore to the main host manually"
      type:
        type: integer
        description: "1 A record, 2 CNAME"
      usedType:
        type: integer
        description: "Usage Record, host_value 0, ip_backup_01 1, ip_backup_02 2 and cname_backup 3"

  monitorAlarmInfo:
    type: object
    x-jdcloud-module: clouddnsservice
    properties:
      domainId:
        type: integer
        description: "Domain Name ID"
      subDomainName:
        type: string
        description: "Subdomain"
      host:
        type: string
        description: "Fault IP/Domain Name"
      id:
        type: integer
        description: 
      startTime:
        type: integer
        description: "Fault Start Time"