swagger: "2.0"
definitions:
  dockerRegistryData:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: "Secret Data"
    required:
      - server
      - username
      - password
    properties:
      server:
        type: string
        description: "Registry Server Address"
      username:
        type: string
        description: "User Name"
      password:
        type: string
        description: "Password " 
      email:
        type: string
        description: "Email Address"