swagger: "2.0"
definitions:
  elasticIpSpec:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: 
    required:
      - bandwidth
    properties:
      bandwidthMbps:
        type: integer
        description: "Elastic IP Speed Limit   Unit: MB  "  
      provider:
        type: string    
        description: "IP Service Provider, value: bgp or no_bg    "    
      chargeSpec:
        $ref: "../../charge/model/ChargeSpec.yaml#/definitions/chargeSpec"
        description: "Billing Configuration" 