swagger: "2.0"
definitions:
  quota:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    properties:
      limit:
        type: integer
        description: "Quota"
      used:
        type: integer
        description: "Used Number"