swagger: "2.0"
definitions:
  securityGroupSimple:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: "Describe basic information of network interface security group"
    properties:
      groupId:
        type: string
        description: "Security Group ID"
      groupName:
        type: string
        description: "Security Group Name"