swagger: "2.0"
definitions:
  volumeMountSpec:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: "Disk Classification Cloud: According to Cloud Disk Service volume, root volume can only be the cloud type."
    required:
      - category
    properties:
      category:
        type: string  
        description: "Disk Classification Cloud: According to Cloud Disk Service volume, root volume can only be the cloud type. " 
      autoDelete:
        type: boolean  
        description: "Automatic deletion, the volume is automatically deleted at the time the container is deleted; the value is True by default; and only the scenario of Cloud Disk Service is supported."
      mountPath:
        type:  string  
        description: "Catalog mounted into the container; it is not required to specify catalog for the root volume and the mounted catalog is (/); a catalog must be specified for the data volume, which must be the absolute path without any (:). " 
      readOnly:
        type: boolean  
        description: "Read-only, false by default; only valid to data volume; when root volume is false, both write and read are available. " 
      cloudDiskSpec:
        $ref: "../../disk/model/DiskSpec.yaml#/definitions/diskSpec"
        description: "Cloud Disk Service specification; the Cloud Disk Service automatically created with the container will not divide the disk and will only format the file system. " 
      # localDiskIndex:
      #   type:   int  
      #   description:  Local disk index; the local disk of the instance type family will not be divided and the file system type can be specified. 
      cloudDiskId:
        type: string  
        description: "Cloud Disk Service ID; if the existing cloud disk is used, be sure to specify partion and fsType. " 
      fsType:
        type: string  
        description: "Specify volume file system type and support [xfs, ext4] now; if the file system type is not specified for the newly-created disk, such disk will be formatted to xfs by default. " 
      formatVolume:
        type: boolean 
        description: "A new disk automatically created with the container will be automatically formatted to the specified file system type; the existing disk mounted will not be formatted by default and only will be mounted as per specified fsType; and if you intend to format the mounted disk, be sure to set the field as true. " 