swagger: "2.0"
info:
  version: "v1"
  title: JCS for Redis Instance Type APIs
  description: "JCS for Redis Instance Type Related APIs"

basePath: /regions/{regionId}

paths:
  "/instanceClass":
    ###################### Query Specification List ######################
    get:
      description: "Query the instance list type under a certain region"
      operationId: describeInstanceClass
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  instanceClasses:
                    type: array
                    items:
                      $ref: "../model/InstanceClass.yaml#/definitions/instanceClass"
                  totalCount:
                    type: integer
              requestId:
                type: string

    ###################### Modify Specification ######################
    patch:
      description: "Modify specification"
      operationId: modifyInstanceClass
      x-jdcloud-internal: true
      parameters:
        - name: instanceClass
          in: query
          required: true
          type: string
          description: "Specification Code"
        - name: actionType
          in: query
          required: true
          type: integer
          description: "Operation, 1 means visible, 0 means invalid, -1 means not visible"
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
