swagger: "2.0"
definitions:
  dwTableRow:
    x-jdcloud-module: xdata
    title: DwTableRow
    type: object
    properties:
      columnName:
        type: string
        description: "Field Name"
      columnType:
        type: string
        description: "Field Type"
      isPartition:
        type: boolean
        description: "Is the field partitioned"
      comments:
        type: string
        description: "Description Information"