swagger: "2.0"
definitions:
  addPermissionsInfo:
    x-jdcloud-module: iam
    required:
      - permissionIds
    properties:
      permissionIds:
        type: array
        items:
          type: integer
        description: "Permissions id Set"


