swagger: "2.0"
definitions:
  azMappingVo:
    x-jdcloud-module: iam
    properties:
      laz:
        type: string
        description: "Logic Az"
      paz:
        type: string
        description: "Physical Az"
