swagger: "2.0"
definitions:
  baseProductRegionVo:
    x-jdcloud-module: iam
    properties:
      serviceCode:
        type: string
        description: "Product Code"
      regionAzVos:
        type: array
        items:
          $ref: "./RegionAzVo.yaml#/definitions/regionAzVo"
        description: "Az Information"
