swagger: "2.0"
definitions:
  createPermissionInfo:
    x-jdcloud-module: iam
    required:
      - name
      - version
      - content
    properties:
      name:
        type: string
        description: "Permission Name, 1~32 numbers, letters, Chinese characters, underlines, underlines and line-throughs"
      description:
        type: string
        description: "Description, 0~256 characters"
      content:
        type: array
        items:
          $ref: "./PermissionDetail.yaml#/definitions/permissionDetail"
        description: "Permission Details"
