swagger: "2.0"
definitions:
  emailSmsInfo:
    x-jdcloud-module: iam
    required:
      - createPin
      - sendType
      - receives
      - templateId
      - templateParam
      - smsMessageSource
    properties:
      createPin:
        type: string
        description: "User Pin"
      title:
        type: string
        description: "Email Subject"
      sendType:
        type: integer
        description: "Sending Type, 1-Sending Email, 2-Sending SMS"
      content:
        type: string
        description: "Email Content"
      receives:
        type: array
        items:
          type: string
        description: "Recipient"
      templateId:
        type: integer
        description: "Template Code"
      templateParam:
        type: array
        items:
          type: string
        description: "Template Parameter"
      smsMessageSource:
        type: string
        description: "Business Code (and Product Application)"