swagger: "2.0"
definitions:
  regionAzVo:
    x-jdcloud-module: iam
    properties:
      alias:
        type: string
        description: "Alias"
      region:
        type: string
        description: "Region"
      visible:
        type: integer
        description: "Visible or Not (1-Yes, 0-No)"
      azStatusList:
        type: array
        items:
          $ref: "./AzSaleStatusVo.yaml#/definitions/azSaleStatusVo"
        description: "Az Status Information"
