swagger: "2.0"
definitions:
  roleInfo:
    x-jdcloud-module: iam
    properties:
      path:
        type: string
        description: "Role Path"
      roleId:
        type: string
        description: "Role ID"
      roleName:
        type: string
        description: "Role Name"
      assumeRolePolicyDocument:
        type: string
        description: "Role Assumption Policy"
      description:
        type: string
        description: "Description, 0~256 characters"
      maxSessionDuration:
        type: integer
        description: "Maximum session duration is 3,600~43,200 seconds, 3,600 seconds by default"
      jrn:
        type: string
        description: "Resource Description"
      createTime:
        type: string
        description: "Role Creation Time"
      account:
        type: string
        description: "Primary Account of Owner"




