swagger: "2.0"
definitions:
  updateAssumeRolePolicyInfo:
    x-jdcloud-module: iam
    properties:
      assumeRolePolicyDocument:
        type: string
        description: "Role Assumption Policy"

