swagger: "2.0"
definitions:
  userResVo:
    x-jdcloud-module: iam
    properties:
      pin:
        type: string
        description: "User Pin"
      cscPhone:
        type: string
        description: "User’s Mobile Number"
      cscEmail:
        type: string
        description: "User’s Email"
      createTime:
        type: string
        format: date-time
        description: "Creation Time"
      userType:
        type: integer
        description: "User Type"
      companyName:
        type: string
        description: "Company Name"
      userType:
        type: integer
        description: "User Type"
      companyName:
        type: string
        description: "Company Name"
      name:
        type: string
        description: "Name"
      arrearageTime:
        type: string
        format: date-time
        description: "Amount Overdue Time"
      userTagObject:
        $ref: "./Flags.yaml#/definitions/flags"
        description: "User Label:"
      attachment:
        $ref: "./UserAttachment.yaml#/definitions/userAttachment"
        description: "User Label:"
