swagger: "2.0"
definitions:
  userAttachment:
    x-jdcloud-module: iam
    properties:
      remark:
        type: string
        description: "Company Name"
      industry:
        type: string
        description: "Industry of Main Business"
      subIndustry:
        type: string
        description: "Sub-option of Main Business"
      business:
        type: string
        description: "Main Business"
      website:
        type: string
        description: "Website"
      cpState:
        type: string
        description: "Country"
      cpProvince:
        type: string
        description: "Province"
      cpCity:
        type: string
        description: "City"
      cpCountry:
        type: string
        description: "District and County"
      cpAddress:
        type: string
        description: "Detailed Address"
      cpTelphone:
        type: string
        description: "Contact Mobile Number"