swagger: "2.0"
definitions:
  userAccessKey:
    x-jdcloud-module: iam
    properties:
      accessKey:
        type: string
        description: accessKey
      accessKeySecret:
        type: string
        description: accessKeySecret
      createTime:
        type: string
        description: "Creation Time"
      state:
        type: integer
        description: "Disabled/Enabled Status [0-Disabled, 1-Enabled]"
      yn:
        type: integer
        description: "Deleted/Valid Status [0-Deleted, 1-Valid]"
