swagger: "2.0"
info:
  version: "v1"
  title: Quota
  description: "Quota APIs"

basePath: /regions/{regionId}

paths:
  "/quotas":
    ###################### Query Quota ######################
    get:
      description: |
        Query quota, support: VM, image, key pair, template
      operationId: describeQuotas
      parameters:
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: | 
            resourceTypes - Resource types, multiple support [instance, keyair, image, instanceTemplate]
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  quotas:
                    type: array
                    description: "Quota list"
                    items:
                      $ref: "../model/Quota.yaml#/definitions/quota"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### Modify Quota ######################
    patch:
      description: |
        Modify quotas; an internal API; support: VM, image, key pair, template
      operationId: modifyQuota
      x-jdcloud-internal: true
      parameters:
        - name: resourceType
          in: query
          type: string
          description: "Source Type [instance, keypair, image, instanceTemplate]"
        - name: limit
          in: query
          type: integer
          description: "Upper Quota Limit"
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID"