swagger: "2.0"
definitions:
  cleanThresholdSpec:
    type: object
    x-jdcloud-module: baseanti
    properties:
      cleanThresholdBps:
        type: integer
        format: int64
        description: "Traffic Rate of Trigger Cleaning, Unit: bps, Ranging from 10000000 to 300000000"
        required: true
      cleanThresholdPps:
        type: integer
        format: int64
        description: "Package Rate of Trigger Cleaning, Unit: pps, Ranging from 2000 to 70000"
        required: true
