swagger: "2.0"
definitions:
  ipResourceFlowDetail:
    type: object
    x-jdcloud-module: baseanti
    properties:
      used:
        type: array
        description: "Use Value of Corresponding Time Point"
        items:
          type: integer
          format: int64
      times:
        type: array
        description: "Time Point"
        items:
          type: string