swagger: "2.0"
info:
  version: "v1"
  title: Consumer Group APIs
  description: "Information APIs related to Stream Hub ConsumerGroup"
basePath: '/regions/{regionId}'
paths:
#######View all the consumer groups of the assigned subject################
  /consumerGroupList:
    get:
      description: "View all the consumer groups of the assigned subject"
      operationId: getConsumerGroupList
      parameters:
        - name: topicId
          type: integer
          in: query
          description: "Subject ID"
          required: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              requestId:
                type: string
              result:
                properties:
                  consumerGroup:
                    type: array
                    items:
                      type: object
                      $ref: "../model/consumerGroupList.yaml#/definitions/consumerGroup"
        400:
            description: UNAUTHENTICATED   
###################Create ConsumerGroupName##############################
  /consumerGroup:
    post:
      description: "Create consumerGroupName"
      operationId: createConsumerGroup
      parameters:
        - name: consumerGroupStr
          in: body
          description: "Consumer Group Object"
          schema:
            $ref: "../model/consumerGroupList.yaml#/definitions/consumerGroup"
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  message:
                    type: string
                  status:
                    type: boolean
              requestId:
                type: string
        '400':
          description: UNAUTHENTICATED
        '401':
          description: STREAMHUB_UNAUTHENTICATED
###################Delete ConsumerGroupName##############################
    delete:
      description: "Delete ConsumerGroupName"
      operationId: deleteConsumerGroup
      parameters:
        - name: topicId
          type: integer
          format: int64
          in: query
          description: "Subject ID"
          required: true
        - name: consumerGroupId
          in: query
          type: integer
          format: int64
          description: "Consumer Group ID"
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  message:
                    type: string
                  status:
                    type: boolean
              requestId:
                type: string
        '400':
          description: UNAUTHENTICATED
        '401':
          description: STREAMHUB_UNAUTHENTICATED

parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID


