swagger: '2.0'
definitions:
  storage:
    x-jdcloud-module: streamcomputer
    title: storage
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      uid:
        type: string
      type:
        type: string
      storageType:
        type: string
        description: "This parameter has two optional values, input and ouput, depending on whether the input or output is created"
      userName:
        type: string
      createTime:
        type: string
        format: date
      updateTime:
        type: string
        format: date  
      namespaceId:
        type: string
      deleted:
        type: string
        format: byte
      storageParameterList:
        type: array
        description: "Specific parameters of Storage. <br>1. When the created source type is streaming data input, source, topicName, duration, format, delimiter, and schema need to be transmitted. <br> 2. When creating output, if the output location is the Stream Hub, topicName, format, delimiter, ossFlag, bucketName, directory and objectName need to be transmitted. <br> 3. When creating output, if the output location is the data compute, database, table, ossFlag, bucketName, directory and objectName need to be transmitted."
        items:
            $ref: "../model/StorageParameter.yaml#/definitions/storageParameter"
            
 