swagger: "2.0"
definitions:
  tag:
    x-jdcloud-module: disk
    properties:
      key:
        type: string
        description: "Tag Key"
      value:
        type: string
        description: "Tag Value"
