swagger: "2.0"
info:
  version: "v1"
  title: Quota
  description: "Container Quota"

basePath: /regions/{regionId}

paths:
  "/quotas":
    ###################### Search Quota ######################
    get:
      description: |
        Search resource quota and support Native Container and secret.
      operationId: describeQuota
      parameters:
        - name: resourceType
          in: query
          type: string
          required: true
          description: |
            resourceType - Resource type, support many [container, secret]
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  quota:
                    $ref: "../model/Quota.yaml#/definitions/quota"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"
    ###################### Modify Quota ######################
    patch:
      description: |
        Modify resource quota and support Native Container and secret.
      operationId: modifyQuota
      x-jdcloud-internal: true
      parameters:
        - name: resourceType
          in: query
          type: string
          required: true
          description: |
            resourceType - Resource type, support many [container, secret]
        - name: limit
          in: query
          type: integer
          required: true
          description: "Cap"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
