swagger: "2.0"
definitions:
  az:
    x-jdcloud-module: cps
    title: az
    type: object
    properties:
      region:
        type: string
        description: "Region Code, such as cn-east-1"
      az:
        type: string
        description: "Availability Zone Code, such as cn-east-1a"
      azName:
        type: string
        description: "Availability Zone Name"
