swagger: "2.0"
definitions:
  deviceType:
    x-jdcloud-module: cps
    title: deviceType
    type: object
    properties:
      nameEN:
        type: string
        description: "English Name of Instance Type Family, such as cps.c.normal"
      nameZH:
        type: string
        description: "Chinese Name of Instance Type Family, such as 计算型"
      useTypeEN:
        type: string
        description: "English Description of Image Type, such as Standard"
      useTypeZH:
        type: string
        description: "Chinese Description of Image Type, such as 标准型"
      region:
        type: string
        description: "Region Code, such as cn-east-1"
      cpuConcise:
        type: string
        description: "CPU Summary Description"
      cpuDetail:
        type: string
        description: "CPU Details"
      memConcise:
        type: string
        description: "Memory Summary Information"
      memDetail:
        type: string
        description: "Memory Details"
      ifConcise:
        type: string
        description: "Summary Information of Network Port"
      ifDetail:
        type: string
        description: "Details of Network Port"
      systemDiskConcise:
        type: string
        description: "Summary Information of System Disk"
      systemDiskDetail:
        type: string
        description: "Details of System Disk"
      dataDiskConcise:
        type: string
        description: "Summary Information of Data Disk"
      dataDiskDetail:
        type: string
        description: "Details of Data Disk"
      gpuConcise:
        type: string
        description: "GPU Summary Information"
      gpuDetail:
        type: string
        description: "GPU Details"