swagger: "2.0"
definitions:
  instanceSpec:
    x-jdcloud-module: cps
    title: instanceSpec
    type: object
    required:
      - az
      - deviceType
      - imageType
      - osTypeId
      - sysRaidTypeId
      - dataRaidTypeId
      - networkType
      - name
      - password
      - count
      - charge
    properties:
      az:
        type: string
        description: "Availability Zone, such as cn-east-1"
      deviceType:
        type: string
        description: "Instance Type Family, such as cps.c.normal"
      imageType:
        type: string
        description: "Image Type, Value Range: Standard, Standard_app"
      osTypeId:
        type: string
        description: "Operating System Type ID"
      sysRaidTypeId:
        type: string
        description: "System Disk RAID Type ID"
      dataRaidTypeId:
        type: string
        description: "Data Disk RAID Type ID"
      subnetId:
        type: string
        description: "Subnet Number"
      enableInternet:
        type: string
        default: "yes"
        description: "Whether to Enable Internet, Value Range: yes/no"
      networkType:
        type: string
        description: "Network Type, Currently Only Support Basic"
      cidr:
        type: string
        description: "Network CIDR"
      lineType:
        type: string
        description: "Internet Link Type, Currently Only Support Bgp"
      bandwidth:
        type: integer
        description: "Internet bandwidth, Range [1,200] Unit: Mbps"
      name:
        type: string
        description: "Name of Cloud Physical Server"
      description:
        type: string
        description: "Description of Cloud Physical Server"
      password:
        type: string
        description: "Password"
      count:
        type: integer
        description: "Purchase Count"
      charge:
        $ref: "../../charge/model/ChargeSpec.yaml#/definitions/chargeSpec"
        description: "Billing Configuration"
      softwares:
        type: array
        items:
          $ref: "../model/Software.yaml#/definitions/software"
