swagger: "2.0"
definitions:
  raid:
    x-jdcloud-module: cps
    title: raid
    type: object
    properties:
      volumeType:
        type: string
        description: Disk Type, such as System/Data
      volumeDetail:
        type: string
        description: Device Details
      raidTypeId:
        type: string
        description: RAID Type ID
      raidType:
        type: string
        description: RAID Type, such as NORAID, RAID0, and RAID1
      deviceType:
        type: string
        description: Type of Cloud Physical Server, such as cps.c.normal
      description:
        type: string
        description: RAID Type Description