swagger: "2.0"
definitions:
  software:
    x-jdcloud-module: cps
    title: software
    type: object
    properties:
      name:
        type: string
        description: "Software Package Name"
      version:
        type: string
        description: "Software Package Version"
      osTypeId:
        type: string
        description: "Operating System Type ID"
      description:
        type: string
        description: "Software Package Description"
