swagger: "2.0"
info:
  version: "v1"
  title: Anti-DDoS Basic APIs
  description: "Anti-DDoS Basic APIs"

basePath: /regions/{regionId}

paths:
  /ipResources:
    get:
      description: "Search the EIP resource list under the zone"
      operationId: describeIpResources
      parameters:
        - name: ip
          in: query
          type: string
          required: false
          description: "IP Fuzzy Matching"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  dataList:
                    type: array
                    items:
                      $ref: "../model/IpResource.yaml#/definitions/ipResource"
                  totalCount:
                    type: integer
              requestId:
                type: string
  /ipResources/{ip}:
    get:
      description: "Search the EIP basic information"
      operationId: describeIpResourceInfo
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  data:
                    $ref: "../model/IpResourceInfo.yaml#/definitions/ipResourceInfo"
              requestId:
                type: string
        404:
          description: NOT_FOUND

  /ipResources/{ip}:setCleanThreshold:
    post:
      description: "Set the EIP cleaning threshold"
      operationId: setCleanThreshold
      parameters:
        - name: cleanThresholdSpec
          in: body
          description: "cc Parameter"
          required: true
          schema:
            $ref: "../model/CleanThresholdSpec.yaml#/definitions/cleanThresholdSpec"
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
        404:
          description: NOT_FOUND

  /ipResources/{ip}/protectInfo:
    get:
      description: "Search EIP protection details"
      operationId: describeIpResourceProtectInfo
      parameters:
        - name: start
          in: query
          type: integer
          required: false
          description: "Start range of limited search"
        - name: limit
          in: query
          type: integer
          required: false
          description: "Records of Limited Search"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  dataList:
                    type: array
                    items:
                      $ref: "../model/IpResourceProtectInfo.yaml#/definitions/ipResourceProtectInfo"
              requestId:
                type: string
        404:
          description: NOT_FOUND

  /ipResources/{ip}/monitorFlow:
    get:
      description: "Search the EIP monitoring traffic"
      operationId: describeIpResourceFlow
      parameters:
        - name: endTime
          in: query
          type: string
          required: false
          description: "Search end time, UTC time, format: yyyy-MM-dd'T'HH:mm:ssZ"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  data:
                    $ref: "../model/IpResourceFlow.yaml#/definitions/ipResourceFlow"
              requestId:
                type: string
        404:
          description: NOT_FOUND

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Belonging Region ID"
  ip:
    name: ip
    in: path
    required: true
    type: string
    description: "EIP Address"
