swagger: "2.0"
info:
  version: "v1"
  title: Cloud Physical Server
  description: CPS Region Operation APIs

paths:
  "/regions":
    ###################### Cloud Physical Server Region List Query ######################
    get:
      description: "Cloud Physical Server Region List Query"
      operationId: describeRegiones
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  regions:
                    type: array
                    items:
                      $ref: "../model/Region.yaml#/definitions/region"
              requestId:
                type: string
        400:
          description: "Bad request"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"