swagger: "2.0"
info:
  version: "v1"
  title: instance
  description: API related to XDATA-DW instances

basePath: /regions/{regionId}

paths:
  "/dwInstance":
    ###################### Obtain a DW instance list ######################
        get:
          description: "Search the instance information of the user"
          operationId: listInstanceInfo
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                      data:
                        type: array
                        items:
                          $ref: "../model/DwInstance.yaml#/definitions/dwInstance"
                  requestId:
                    type: string
            500:
              description: "Internal server error"

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID"