swagger: "2.0"
info:
  version: "v1"
  title: table
  description: API related to XDATA-DW table

basePath: /regions/{regionId}

paths:
  "/dwTable":
    ###################### Obtain all the datasheets under the specified database ######################
        get:
          description: "Search all the datasheet information under the specified database of user instance"
          operationId: listTableInfo
          parameters:
            - name: instanceName
              in: query
              type: string
              required: true
              description: "Instance Name"
            - name: databaseName
              in: query
              type: string
              required: true
              description: "Database Name"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                      data:
                        type: array
                        items:
                          $ref: "../model/DwTable.yaml#/definitions/dwTable"
                  requestId:
                    type: string
            500:
              description: "Internal server error"

    ###################### Create a datasheet ######################
        post:
          description: "Create a user instance datasheet"
          operationId: createTable
          parameters:
            - name: instanceName
              in: query
              type: string
              required: true
              description: "Instance Name"
            - name: dbModelDBTable
              in: body
              required: true
              description: "Datasheet Description Information"
              schema:
                $ref: "../model/DwTableDesc.yaml#/definitions/dwTableDesc"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                  requestId:
                    type: string

  "/dwTable/{tableName}":
    ###################### View the specified datasheet information ######################
        get:
          description: "Search the specified datasheet information of user instance"
          operationId: getTableInfo
          parameters:
            - name: instanceName
              in: query
              type: string
              required: true
              description: "Instance Name"
            - name: databaseName
              in: query
              type: string
              required: true
              description: "Database Name"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                      data:
                        $ref: "../model/DwTable.yaml#/definitions/dwTable"
                  requestId:
                    type: string
            500:
              description: "Internal server error"

    ###################### Delete a datasheet ######################
        delete:
          description: "Delete a specified datasheet of user instance"
          operationId: deleteTable
          parameters:
            - name: instanceName
              in: query
              type: string
              required: true
              description: "Instance Name"
            - name: databaseName
              in: query
              type: string
              required: true
              description: "Database Name"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                      data:
                        type: object
                  requestId:
                    type: string
            500:
              description: "Internal server error"

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID"
  tableName:
    name: tableName
    in: path
    required: true
    type: string
    description: "Datasheet Name"