swagger: "2.0"
info:
  version: "v1"
  title: AuditLog Request
  description: JMR audit log,including cluster executing history etc. Fron end request interface

basePath: /regions/{regionId}
paths:
 ###################### Query Metric Data ######################
  "/{clusterId}/history:list":
       post:
         description: "View the cluster history"
         operationId: listClusterHistory
         x-jdcloud-internal: true
         parameters:
           - name: clusterId
             in: path
             required: true
             type: string
             description: "Cluster ID"
           - name: selectParams
             in: body
             required: false
             schema:
               $ref: "../model/SelectParams.yaml#/definitions/selectParams"
         responses:
           200:
             description: OK
             schema:
               properties:
                 result:
                   properties:
                     status:
                       type: string
                     message:
                       type: string
                     data:
                       type: object
                       schema:
                         properties:
                           totalNum:
                             type: integer
                             description: "Number of Audit Log Lists Returned"
                           auditLogList:
                             type: array
                             items:
                               $ref: "../model/AuditLog.yaml#/definitions/auditLog"
                       description: |
                                    "Include log list - auditLogList"
                                    "And returned list size - totalNum"
                 requestId:
                   type: string
           500:
             description: "Internal server error"
# Path General Parameters
parameters:
 regionId:
   name: regionId
   in: path
   required: true
   type: string
   description: "Region ID"