swagger: "2.0"
info:
  version: "v1"
  title: Monitor
  description: JMR Monitor

basePath: /regions/{regionId}
paths:
 ###################### Query Metric Data ######################
  "/metricData/{clusterId}:query":
       post:
         description: "Search Metric Data"
         operationId: queryMetricData
         x-jdcloud-internal: true
         parameters:
           - name: clusterId
             in: path
             required: true
             type: string
             description: "Cluster ID"
           - name: timeInterval
             in: query
             required: true
             type: string
             description: "Search interval duration, such as 1h"
         responses:
           200:
             description: OK
             schema:
               properties:
                 result:
                   properties:
                     status:
                       type: string
                     message:
                       type: string
                     data:
                       type: array
                       items:
                         $ref: "../model/Metrics.yaml#/definitions/metrics"
                 requestId:
                   type: string
           500:
             description: "Internal server error"
 ###################### Query Metric Data ######################
  "/{clusterId}/nodeInfo:list":
       post:
         description: "Search the detailed information of nodes under the cluster"
         operationId: queryNodeInfoList
         x-jdcloud-internal: true
         parameters:
           - name: clusterId
             in: path
             required: true
             type: string
             description: "Cluster ID"
         responses:
           200:
             description: OK
             schema:
               properties:
                 result:
                   properties:
                     status:
                       type: string
                     message:
                       type: string
                     data:
                       type: array
                       items:
                         $ref: "../model/NodeInfoData.yaml#/definitions/nodeInfoData"
                 requestId:
                   type: string
           500:
             description: "Internal server error"
# Path General Parameters
parameters:
 regionId:
   name: regionId
   in: path
   required: true
   type: string
   description: "Region ID"