swagger: "2.0"
definitions:
  clusterDetailModel:
    x-jdcloud-module: jmr
    title: clusterDetailModel
    type: object
    properties:
      id:
        type: string
        description: "Cluster ID"
      name:
        type: string
        description: "Cluster name allows Chinese, numbers, capital and lowercase letters, English underline “_” and line-through “-”, with the length of 6-32 characters."
      clusterPrimaryId:
        type: integer
        format: int64
        description: "Cluster Primary Key ID"
      status:
        type: string
        description: "Cluster Status"
      nodeCount:
        type: integer
        description: "Node Number"
      payType:
        type: string
        description: "Payment Type"
      payPrice:
        type: string
        description: "Payment Price"
      createTime:
        type: string
        format: date-time
        description: "Creation Time"
      duration:
        type: string
        description: "Operating Hours"
      hardware:
        type: array
        items:
          $ref: "./HardwareInfo.yaml#/definitions/hardwareInfo"
      softwareStack:
        type: object
        description: "Software Information"
        properties:
          version:
            type: string
            description: "Version"
          software:
            type: string
            description: "Software List"
      dataCenter:
        type: string
        description: "Region, the same as regionID"
      jssFlag:
        type: boolean
        description: "Whether to associate the Object Storage Service or not"
      haFlag:
        type: boolean
        description: "Whether it is high availability mode or not"
      vpcName:
        type: string
        description: "Name of Virtual Private Cloud"
      vpcSubnetName:
        type: string
        description: "Subnet Name"
      bandwidthOut:
        type: integer
        description: "Network Bandwidth"