swagger: "2.0"
definitions:
  clusterModel:
    x-jdcloud-module: jmr
    title: clusterModel
    type: object
    properties:
      name:
        type: string
        required: true
        description: "Cluster name allows Chinese, numbers, capital and lowercase letters, English underline “_” and line-through “-”, with the length of 6-32 characters."
      password:
        type: string
        required: true
        description: |
          "Cluster Password"
          "1. It must include three types of the capital letters, lowercase letters, numbers and special characters, and cannot be less than 8 characters nor exceed 30 characters"
          "2. Special characters are as follows!@#$%^*"
          "3. Characters or complete words that cannot be included are as follows: jd, JD, 360, bug, BUG, com, COM, jcloud, JCLOUD, cloud, CLOUD, password, PASSWORD"
          "4. Consecutive numbers cannot be included, such as: 123, 987"
          "5. Consecutive or key mapping consecutive letters cannot be included, such as abc, CBA, bcde, qaz, tfc, zaq, and qwer"
          "6. Password can't include your PIN"
      version:
        type: string
        required: true
        description: |
          "Software service Version, please fill in one of the following lists:"
          "JMR1.0.0"
          "JMR1.0.1"
          "JMR1.0.2"
          "JMR2.0.0"
          "JMR_BD-OS-1.0"
      payType:
        type: string
        required: true
        description: |
          "Payment type, please fill in one of the following lists:"
          "By Amount"
      #payPrice:
        #type: string
        #required: true
        #description: Billing Price
      masterNodeNumber:
        type: integer
        required: true
        description: "Master Node Number"
      #masterCore:
        #type: integer
        #required: true
        #description: Master Node CPU
      #masterMemory:
        #type: integer
        #required: true
        #description: Master Node Memory (At least 8G memory is recommended; otherwise the service may fail to deploy)
      masterNodeDiskType:
        type: string
        description: |
          "Master node cloud disk type, the optional types are (the following types are separated with "/")"
          "NBD/NBD_SATA"
          "Respectively Stand for: Performance Type/Capacity Type"
      masterNodeDiskVolume:
        type: integer
        description: "Master node cloud disk capacity must be the integral multiples of 10, but greater than 20 and less than 3000GB"
      masterInstanceType:
        type: string
        required: true
        description: "Master node specification, such as: g.n1.xlarge; please refer to [document](https://www.jdcloud.com/help/detail/296/isCatalog/1) for more specification"
      slaveNodeNumber:
        type: integer
        required: true
        description: "Slave Node Number"
      #slaveCore:
        #type: integer
        #required: true
        #description: Slave Node CPU
      #slaveMemory:
        #type: integer
        #required: true
        #description: Slave Node Memory (At least 4G memory is recommended; otherwise the service may fail to deploy)
      slaveNodeDiskType:
        type: string
        description: |
          "Slave node cloud disk type, the optional types are (the following types are separated with "/")"
          "NBD/NBD_SATA"
          "Respectively Stand for: Performance Type/Capacity Type"
      slaveNodeDiskVolume:
        type: integer
        description: "Slave node cloud disk capacity must be the integral multiples of 10, but greater than 20 and less than 3000GB"
      coreInstanceType:
        type: string
        required: true
        description: "Core node specification, such as: g.n1.xlarge; please refer to [document](https://www.jdcloud.com/help/detail/296/isCatalog/1) for more specification"
      dataCenter:
        type: string
        default: cn-north-1
        description: "Region, the same as regionID"
      softwareList:
        type: string
        default: HADOOP,ZOOKEEPER
        description: "Software list, different software shall be separated with English comma (,); refer to [document](https://www.jdcloud.com/help/detail/1323/isCatalog/1)"
      jssFlag:
        type: boolean
        default: false
        description: "Whether to associate the Object Storage Service or not"
      haFlag:
        type: boolean
        default: true
        description: "Whether the cluster is in high availability mode or not"
      vpcId:
        type: string
        default: new
        description: "VPC ID"
      vpcSubnetId:
        type: string
        default: new
        description: "Subnet UUID can be obtained by querying the subnet list"
      bandwidth:
        type: integer
        default: 5
        description: "Network Bandwidth Cap"