swagger: "2.0"
definitions:
  clusterDetailInfo:
    x-jdcloud-module: jmr
    title: clusterDetailInfo
    type: object
    properties:
      materNum:
        type: integer
        description: "Master Node Number"
      masterCore:
        type: integer
        required: true
        description: "Master Node CPU"
      masterMemory:
        type: integer
        required: true
        description: "Master Node Memory (At least 8G memory is recommended; otherwise the service may fail to deploy)"
      masterDiskType:
        type: string
        description: |
                  "Master node cloud disk type, the optional types are (the following types are separated with "/")"
                  "NBD/NBD_SATA"
                  "Respectively Stand for: Performance Type/Capacity Type"
      masterDiskVolume:
        type: integer
        description: "Master node cloud disk capacity must be the integral multiples of 10, but greater than 20 and less than 3000GB"
      masterInstanceType:
        type: string
        required: true
        description: "Master node specification, such as: g.n1.xlarge; please refer to [document](https://www.jdcloud.com/help/detail/296/isCatalog/1) for more specification"
      masterInstanceInfo:
        type: string
        description: "Master Node Instance Information"
      slaveNum:
        type: integer
        required: true
        description: "Slave Node Number"
      slaveCore:
        type: integer
        required: true
        description: "Slave Node CPU"
      slaveMemory:
        type: integer
        required: true
        description: "Slave Node Memory (At least 4G memory is recommended; otherwise the service may fail to deploy)"
      slaveDiskType:
        type: string
        description: |
            "Slave node cloud disk type, the optional types are (the following types are separated with "/")"
            "NBD/NBD_SATA"
            "Respectively Stand for: Performance Type/Capacity Type"
      slaveDiskVolume:
        type: integer
        description: "Slave node cloud disk capacity must be the integral multiples of 10, but greater than 20 and less than 3000GB"
      slaveInstanceType:
        type: string
        required: true
        description: "Slave node specification, such as: g.n1.xlarge; please refer to [document](https://www.jdcloud.com/help/detail/296/isCatalog/1) for more specification"
      slaveInstanceInfo:
        type: string
        description: "Slave Node Instance Information"
