swagger: "2.0"
definitions:
  clusterExpansion:
    x-jdcloud-module: jmr
    title: clusterExpansion
    type: object
    properties:
      clusterId:
        type: string
        description: "Cluster Id"
      expansionNum:
        type: integer
        description: "Expansion Number"