swagger: "2.0"
definitions:
  clusterListViewModel:
    x-jdcloud-module: jmr
    title: clusterListViewModel
    type: object
    properties:
      userName:
        type: string
        description: "User Name"
      masterNodeInfo:
        type: string
        description: "Master Node Information"
      masterNodeDiskType:
        type: string
        description: "Master Node Disk Type"
      masterNodeDiskVolume:
        type: integer
        description: "Master Node Disk Capacity"
      masterNodeNumber:
        type: integer
        description: "Master Node Number"
      masterInstanceType:
        type: string
        description: "Master Node Instance Type"
      slaveNodeInfo:
        type: string
        description: "Slave Node Information"
      slaveNodeDiskType:
        type: string
        description: "Slave Node Disk Type"
      slaveNodeDiskVolume:
        type: integer
        description: "Slave Node Disk Capacity"
      slaveNodeNumber:
        type: integer
        description: "Slave Node Number"
      coreInstanceType:
        type: string
        description: "Core Instance Type"
      bandwidthOut:
        type: integer
        description: "Network Bandwidth"
      dataCenter:
        type: string
        description: "Data Center Location"