swagger: "2.0"
definitions:
  idata:
    x-jdcloud-module: jmr
    title: idata
    type: object
    properties:
      total:
        type: integer
        description: "Cluster Machine Total Number"
      clusters:
        type: array
        items:
          $ref: "../model/idataCluster.yaml#/definitions/idataCluster"