swagger: "2.0"
definitions:
  jobViewListData:
    x-jdcloud-module: jmr
    title: jobViewListData
    type: object
    properties:
      totalNum:
        type: integer
        description: "Query List Size"
      jobList:
        type: array
        items:
          $ref: "../model/JmrJobViewModel.yaml#/definitions/jmrJobViewModel"