swagger: "2.0"
definitions:
  queryVpcSubnets:
    x-jdcloud-module: jmr
    title: queryVpcSubnets
    type: object
    properties:
      vpcSubnetId:
        type: string
        description: "VPC Subnet ID"
      vpcSubnetName:
        type: string
        description: "VPC Subnet Name"