swagger: "2.0"
definitions:
  scale:
    x-jdcloud-module: jmr
    title: scale
    type: object
    properties:
      core:
        type: integer
        description: "Number of CPU Cores"
      memory:
        type: integer
        description: "Memory Size, Unit: G"