swagger: "2.0"
definitions:
  taskViewListData:
    x-jdcloud-module: jmr
    title: taskViewListData
    type: object
    properties:
      totalNum:
        type: integer
        description: "Query List Size"
      taskList:
        type: array
        items:
          $ref: "../model/JmrTaskViewModel.yaml#/definitions/jmrTaskViewModel"