swagger: "2.0"
info:
  version: "v1"
  title: Quota
  description: K8S Cluster Quota APIs

basePath: /regions/{regionId}

paths:
  "/quotas":
    ###################### Query Quota ######################
    get:
      description: "Query (k8s cluster) quota"
      operationId: describeQuotas
      x-jdcloud-internal: false
      parameters:
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: | 
            resourceTypes - Resource type, currently only support [kubernetes]
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  quotas:
                    type: array
                    description: "Quota list"
                    items:
                      $ref: "../model/Quota.yaml#/definitions/quota"
              requestId:
                type: string

    ###################### Modify Quota ######################
    patch:
      description: "Modify the (k8s cluster) quota, internal API"
      operationId: modifyQuota
      x-jdcloud-internal: true
      parameters:
        - name: resourceType
          in: query
          type: string
          description: Resource Type[kubernetes]
        - name: limit
          in: query
          type: integer
          description: Quota Cap
      responses:
        200:
          description: OK

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID