swagger: "2.0" # realized based on Swagger 2.0 version
info:
  version: "v1"                                 # OpenApi Version Number
  title: SpecialUser APIs
  description: "SpecialUser APIs"

basePath: /regions/{regionId}

paths:
  /:
    post:
      tags:
      - developers
      summary: update bucket max count
      operationId: updateBucketMaxCount
      x-jdcloud-internal: true
      description: |
        Update bucket maximum
      produces:
      - application/json
      parameters:
      - in: header
        name: bucketmaxcount
        description: "Bucket Maximum, e.g.: 50, Minimum 20"
        required: true
        type: integer
      - in: header
        name: userpin
        description: "Assign user's pin"
        required: true
        type: string
      responses:
        200:
          description: OK
        400:
          description: Invalid Argument
#          schema:
#            $ref: '../model/oss.yaml#/definitions/ErrorResponse'
        403:
          description: Access Denied
#          schema:
#            $ref: '../model/oss.yaml#/definitions/ErrorResponse'
# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID, e.g.: cn-north-1"
