swagger: "2.0" # realized based on Swagger 2.0 version
info:
  version: "v1"                                 # OpenApi Version Number
  title: OSS APIs
  description: "OSS APIs"

basePath: /regions/{regionId}

paths:
  /buckets/{bucketname}:imgProtected:
    put:
      tags:
      - developers
      summary: create imgProtected
      operationId: putImgProtected
      x-jdcloud-internal: true
      description: |
        Create original image protection
      produces:
      - application/json
      parameters:
      - in: path
        name: bucketname
        required: true
        type: string
        description: "Bucket name, e.g.: test"
      - in: query
        name: condition
        description: "Include xml of image suffix to be protected"
        required: true
        type: string
        description: "Original Image Protection Configuration"
      responses:
        200:
          description: OK
        400:
          description: Invalid Argument
#          schema:
#            $ref: '../model/oss.yaml#/definitions/ErrorResponse'
        403:
          description: Access Denied
#          schema:
#            $ref: '../model/oss.yaml#/definitions/ErrorResponse'
        409:
          description: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
#          schema:
#            $ref: '../model/oss.yaml#/definitions/ErrorResponse'
    get:
      tags:
      - developers
      summary: get imgProtected Condition
      operationId: getimgProtectedCondition
      x-jdcloud-internal: true
      description: |
        Obtain original image protection configuration of current bucket
      produces:
      - application/json
      parameters:
      - in: path
        name: bucketname
        required: true
        type: string
        description: "Bucket name, e.g.: test"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  imgProtectedResult:
                    $ref: '../model/imgProtectedResult.yaml#/definitions/Result'
              requestId:
                type: string
#            properties:
        400:
          description: Invalid Argument
#          schema:
#            $ref: '../model/oss.yaml#/definitions/ErrorResponse'
        403:
          description: Access Denied
#          schema:
#            $ref: '../model/oss.yaml#/definitions/ErrorResponse'
    delete:
      tags:
      - developers
      summary: delete imgProtected
      operationId: deleteImgProtected
      x-jdcloud-internal: true
      description: |
        Disable original image protection
      produces:
      - application/json
      parameters:
      - in: path
        name: bucketname
        required: true
        type: string
        description: "Bucket name, e.g.: test"
      responses:
        200:
          description: OK
        400:
          description: Invalid Argument
#          schema:
#            $ref: '../model/oss.yaml#/definitions/ErrorResponse'
        403:
          description: Access Denied
#          schema:
#            $ref: '../model/oss.yaml#/definitions/ErrorResponse'
        404:
          description: The specified bucket does not exist.
#          schema:
#            $ref: '../model/oss.yaml#/definitions/ErrorResponse'
# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID, e.g.: cn-north-1"

