swagger: "2.0"
definitions:
  ag:
    x-jdcloud-module: vm
    properties:
      name:
        type: string
        description: "AG Name"
      id:
        type: string
        description: "AG id"
#      description:
#        type: string
# description: AG id
#      agType:
#        type: string
# description: AZ Type, support compute/container
#      instanceTemplateId:
#        type: string
# description: Id of Start Template
#      azs:
#        type: array
#        items:
#          type: string
# description: AZ
#      count:
#        type: integer
# description: Number of Instances
#      autoScaling:
#        type: boolean
# description: Open automatic scaling or not