swagger: "2.0"
definitions:
  image:
    x-jdcloud-module: vm
    properties:
      imageId:
        type: string
        description: "Image ID"
      name:
        type: string
        description: "Image Name"
      platform:
        type: string
        description: "OS Release Version. Ubuntu, CentOS, Windows Server"
      osVersion:
        type: string
        description: "OS Version."
      architecture:
        type: string
        description: "Image Architecture. Value: i386, x86_64"
      systemDiskSizeGB:
        type: integer
        description: "Image System Disk Size"
      imageSource:
        type: string
        description: "Image source, jcloud: public image, marketplace: image marketplace, image self: user's own image share: image shared by other users"
      osType:
        type: string
        description: "OS type. Value: [windows, linux]"
      status:
        type: string
        description: "<a href='https://www.jdcloud.com/help/detail/3871/isCatalog/1'>refer to image status</a>"
      createTime:
        type: string
        format: date-time
        description: "Creation Time"
      sizeMB:
        type: integer
        description: "Image Document Size"
      desc:
        type: string
        description: "Image Description"
      systemDisk:
        $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: "System Disk Configuration"
      dataDisks:
        type: array
        items:
          $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: "Package Image Data Disk Mapping Information"
      snapshotId:
        type: string
        description: "The snapshot ID of the Cloud Disk Service for creating the system disk of the cloud disk, when the system disk type is image of the local disk, this parameter is blank."
      rootDeviceType:
        type: string
        description: "The system disk type supported by the image. localDisk: Support system disk for this site.cloudDisk: Support cloud disk system disk"
      progress:
        type: string
        description: "Progress in image replication, in percentage, for example: 80"
