swagger: "2.0"
definitions:
  imageConstraint:
    x-jdcloud-module: vm
    properties:
      imageId:
        type: string
        description: "Image ID"
      imageInstanceTypeConstraint:
        description: "Specification limit for instance type created by image"
        $ref: "#/definitions/imageInstanceTypeConstraint"
  imageInstanceTypeConstraint:
    x-jdcloud-module: vm
    properties:
      constraintsType:
        description: "Restricted specification type. Value: excludes: exclude specified instance types; includes: only the specified instance type is included, which is not supported temporarily"
        type: string
      instanceTypes:
        description: "Instance Type List"
        type: array
        items:
          type: string
