swagger: "2.0"
definitions:
  instancePrivateIpAddress:
    x-jdcloud-module: vm
    properties:
      instanceId:
        type: string
        description: "VM ID"
      privateIpAddress:
        type: string
        description: "The primary IP address in the primary network interface"