swagger: "2.0"
definitions:
  instanceTemplateSpec:
    x-jdcloud-module: vm
    required:
      - instanceType
      - imageId
      - primaryNetworkInterface
      - systemDisk
    properties:
      instanceType:
        type: string
        description: "Instance Type, can query<a href='http://docs.jdcloud.com/virtual-machines/api/describeinstancetypes'>DescribeInstanceTypes</a> API for the instance type information of the specified zone or availability zone."
      imageId:
        type: string
        description: "Image ID, can query<a href='http://docs.jdcloud.com/virtual-machines/api/describeimages'>DescribeImages</a> API for the image information of the specified zone."
      password:
        type: string
        description: "Password, <a href='http://docs.jdcloud.com/virtual-machines/api/general_parameters'>Refer to the public parameter specification</a>."
      keyNames:
        type: array
        items:
          type: string
        description: "Key Pair Name; only one is supported  currently"
      elasticIp:
        $ref: "./InstanceTemplateElasticIpSpec.yaml#/definitions/instanceTemplateElasticIpSpec"
        description: "EIP specification associated with the primary IP of the primary network interface"
      primaryNetworkInterface:
        $ref: "./InstanceTemplateNetworkInterfaceAttachmentSpec.yaml#/definitions/instanceTemplateNetworkInterfaceAttachmentSpec"
        description: "Primary Network Interface Configuration Information"
      systemDisk:
        $ref: "./InstanceTemplateDiskAttachmentSpec.yaml#/definitions/instanceTemplateDiskAttachmentSpec"
        description: "System Disk Configuration Information"
      dataDisks:
        type: array
        items:
          $ref: "./InstanceTemplateDiskAttachmentSpec.yaml#/definitions/instanceTemplateDiskAttachmentSpec"
        description: "Data Disk Configuration Information"