swagger: "2.0"
definitions:
  instanceNetworkAttribute:
    x-jdcloud-module: vm
    properties:
      networkInterfaceId:
        type: string
        description: "ENI ID"
      autoDelete:
        type: boolean
        description: "Auto-delete with the machine, False by default."
