swagger: "2.0"
definitions:
  instanceType:
    x-jdcloud-module: vm
    properties:
      family:
        type: string
        description: "Instance Type"
      instanceType:
        type: string
        description: "Instance Type, such as g.b1.2xlarge"
      cpu:
        type: integer
        description: "CPU Number"
      memoryMB:
        type: integer
        description: "Memory Size"
      nicLimit:
        type: integer
        description: "Number of ENI Supported"
      desc:
        type: string
        description: "Description"
      state:
        type: array
        items:
          $ref: "./InstanceTypeState.yaml#/definitions/instanceTypeState"
        description: "Type Status"
      gpu:
        $ref: "./Gpu.yaml#/definitions/gpu"
        description: "Gpu configuration"
      localDisks:
        type: array
        items:
          $ref: "./LocalDisk.yaml#/definitions/localDisk"
        description: "Configuration of local cache disk, only available for Gpu specification"
