swagger: "2.0"
definitions:
  instanceSpec:
    x-jdcloud-module: vm
    required:
      - name
    properties:
      agId:
        type: string
        description: "AG Id. Once this parameter is specified, the VM can only be created by the instance template associated with the AG, and the parameters in the instance template cannot be replaced. Parameters other than the instance template can be specified."
      instanceTemplateId:
        type: string
        description: "Instance template id. If the users do not use an AG, the unavailable information in the instance template needs to be added by the parameters that create the VM, or choose to replace the parameters in the start template."
      az:
        type: string
        description: "The AZ to which the VM belongs."
      instanceType:
        type: string
        description: "Instance Type. Can query <a href='http://docs.jdcloud.com/virtual-machines/api/describeinstancetypes'>DescribeInstanceTypes</a> API for instance type information of the specified zone or availability zone."
      imageId:
        type: string
        description: "Image ID. Can query<a href='http://docs.jdcloud.com/virtual-machines/api/describeimages'>DescribeImages</a>API obtains the image information of the specified zone."
      name:
        type: string
        description: "VM name, <a href='http://docs.jdcloud.com/virtual-machines/api/general_parameters'>Refer to the public parameter specification</a>."
      password:
        type: string
        description: "Password, <a href='http://docs.jdcloud.com/virtual-machines/api/general_parameters'>Refer to the public parameter specification</a>."
      keyNames:
        type: array
        items:
          type: string
        description: "Key Pair Name, currently only supports incoming one."
      elasticIp:
        $ref: "../../vpc/model/ElasticIpSpec.yaml#/definitions/elasticIpSpec"
        description: "EIP specification associated with the primary IP of the primary network interface"
      primaryNetworkInterface:
        $ref: "./InstanceNetworkInterfaceAttachmentSpec.yaml#/definitions/instanceNetworkInterfaceAttachmentSpec"
        description: "Primary Network Interface Configuration Information"
      systemDisk:
        $ref: "./InstanceDiskAttachmentSpec.yaml#/definitions/instanceDiskAttachmentSpec"
        description: "System Disk Configuration Information"
      dataDisks:
        type: array
        items:
          $ref: "./InstanceDiskAttachmentSpec.yaml#/definitions/instanceDiskAttachmentSpec"
        description: "The configuration information of the data disk. The virtual machine with local disk as system disk can be attached with 8 data disks, and 7 data disks for the virtual machine with cloud disk as system disk."
      charge:
        $ref: "../../charge/model/ChargeSpec.yaml#/definitions/chargeSpec"
        description: |
          Billing Configuration
          The VM does not support pay by consumption. The default is pay by configuration.
          In the case of creating a data disk in packages, the billing method of the data disk can only be consistent with the VM.
          In the case of creating EIP in packages, if it is not specified as pay by consumption, the billing method of the public IP can only be consistent with the VM.
      description:
        type: string
        description: "Machine Description, <a href='http://docs.jdcloud.com/virtual-machines/api/general_parameters'>Refer to the public parameter specification</a>."
