swagger: "2.0"
definitions:
  instanceTemplate:
    x-jdcloud-module: vm
    properties:
      id:
        type: string
        description: "Start template ID"
      name:
        type: string
        description: "Start template name"
      description:
        type: string
        description: "Start template description"
      instanceTemplateData:
        $ref: "./InstanceTemplateData.yaml#/definitions/instanceTemplateData"
        description: "Start template data"
      ags:
        type: array
        items:
          $ref: "./Ag.yaml#/definitions/ag"
        description: "AG Information Associated"
      createdTime:
        type: string
        format: date-time
        description: "Creation Time"