swagger: "2.0"
definitions:
  instanceTemplateDisk:
    x-jdcloud-module: vm
    properties:
      diskType:
        type: string
        description: "Cloud Disk Service type, value ssd or premium-hdd"
      diskSizeGB:
        type: integer
        description: "The size of the Cloud Disk Service, unit is GiB; ssd type value range[20, 1000] GB, step size: 10G, premium-hdd type value range[20, 3000] GB, step size: 10G"
      snapshotId:
        type: string
        description: "Snapshot ID used to create Cloud Disk Service"