swagger: "2.0"
definitions:
  instancePrivateIpAddress:
    x-jdcloud-module: vm
    properties:
      instanceId:
        type: string
        description: "VM ID"
      privateIpAddress:
        type: string
        description: "Primary intranet IP of primary network interface"