swagger: "2.0"
definitions:
  instanceTemplateNetworkInterfaceAttachmentSpec:
    x-jdcloud-module: vm
    required:
      - networkInterface
    properties:
      deviceIndex:
        type: integer
        description: "Device Index; The index of the primary network interface must be 1; The primary network interface is currently supported only"
      autoDelete:
        type: boolean
        description: "Indicates whether the network interface is deleted when deleting an instance, and the default is true, which cannot be changed currently"
      networkInterface:
        $ref: "./InstanceTemplateNetworkInterfaceSpec.yaml#/definitions/instanceTemplateNetworkInterfaceSpec"
        description: "Network interface API instance type; this field is currently required"