swagger: "2.0"
definitions:
  keypair:
    x-jdcloud-module: vm
    properties:
      keyName:
        type: string
        description: "Key Pair Name"
      keyFingerprint:
        type: string
        description: "The fingerprint of the key pair, based on the public key fingerprint format defined in RFC4716, the MD5 information digest algorithm is adopted."
      createTime:
        type: string
        description: "Creation Time"